// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrossRank.proto

package com.gzbz.protobuf;

public final class CrossRankMsg {
  private CrossRankMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2CR_UpdateRank_10901OrBuilder extends
      // @@protoc_insertion_point(interface_extends:crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 moduleId = 1;</code>
     * @return Whether the moduleId field is set.
     */
    boolean hasModuleId();
    /**
     * <code>required int32 moduleId = 1;</code>
     * @return The moduleId.
     */
    int getModuleId();

    /**
     * <code>required int32 value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 2;</code>
     * @return The value.
     */
    int getValue();

    /**
     * <code>required int64 score = 3;</code>
     * @return Whether the score field is set.
     */
    boolean hasScore();
    /**
     * <code>required int64 score = 3;</code>
     * @return The score.
     */
    long getScore();

    /**
     * <code>repeated string params = 4;</code>
     * @return A list containing the params.
     */
    java.util.List<java.lang.String>
        getParamsList();
    /**
     * <code>repeated string params = 4;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    java.lang.String getParams(int index);
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    com.google.protobuf.ByteString
        getParamsBytes(int index);
  }
  /**
   * Protobuf type {@code crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901}
   */
  public  static final class S2CR_UpdateRank_10901 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901)
      S2CR_UpdateRank_10901OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2CR_UpdateRank_10901.newBuilder() to construct.
    private S2CR_UpdateRank_10901(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2CR_UpdateRank_10901() {
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2CR_UpdateRank_10901();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2CR_UpdateRank_10901(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              moduleId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              score_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                params_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              params_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          params_ = params_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.CrossRankMsg.internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.CrossRankMsg.internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.class, com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.Builder.class);
    }

    private int bitField0_;
    public static final int MODULEID_FIELD_NUMBER = 1;
    private int moduleId_;
    /**
     * <code>required int32 moduleId = 1;</code>
     * @return Whether the moduleId field is set.
     */
    public boolean hasModuleId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 moduleId = 1;</code>
     * @return The moduleId.
     */
    public int getModuleId() {
      return moduleId_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 value = 2;</code>
     * @return The value.
     */
    public int getValue() {
      return value_;
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private long score_;
    /**
     * <code>required int64 score = 3;</code>
     * @return Whether the score field is set.
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 score = 3;</code>
     * @return The score.
     */
    public long getScore() {
      return score_;
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList params_;
    /**
     * <code>repeated string params = 4;</code>
     * @return A list containing the params.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasModuleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, moduleId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, score_);
      }
      for (int i = 0; i < params_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, params_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, moduleId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, score_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += computeStringSizeNoTag(params_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 other = (com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901) obj;

      if (hasModuleId() != other.hasModuleId()) return false;
      if (hasModuleId()) {
        if (getModuleId()
            != other.getModuleId()) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (getValue()
            != other.getValue()) return false;
      }
      if (hasScore() != other.hasScore()) return false;
      if (hasScore()) {
        if (getScore()
            != other.getScore()) return false;
      }
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModuleId()) {
        hash = (37 * hash) + MODULEID_FIELD_NUMBER;
        hash = (53 * hash) + getModuleId();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getScore());
      }
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901)
        com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.CrossRankMsg.internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.CrossRankMsg.internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.class, com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.Builder.class);
      }

      // Construct using com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        moduleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.CrossRankMsg.internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 getDefaultInstanceForType() {
        return com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 build() {
        com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 buildPartial() {
        com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 result = new com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.moduleId_ = moduleId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.score_ = score_;
          to_bitField0_ |= 0x00000004;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          params_ = params_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901) {
          return mergeFrom((com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 other) {
        if (other == com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901.getDefaultInstance()) return this;
        if (other.hasModuleId()) {
          setModuleId(other.getModuleId());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasModuleId()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        if (!hasScore()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int moduleId_ ;
      /**
       * <code>required int32 moduleId = 1;</code>
       * @return Whether the moduleId field is set.
       */
      public boolean hasModuleId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 moduleId = 1;</code>
       * @return The moduleId.
       */
      public int getModuleId() {
        return moduleId_;
      }
      /**
       * <code>required int32 moduleId = 1;</code>
       * @param value The moduleId to set.
       * @return This builder for chaining.
       */
      public Builder setModuleId(int value) {
        bitField0_ |= 0x00000001;
        moduleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 moduleId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearModuleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        moduleId_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>required int32 value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 value = 2;</code>
       * @return The value.
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }

      private long score_ ;
      /**
       * <code>required int64 score = 3;</code>
       * @return Whether the score field is set.
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 score = 3;</code>
       * @return The score.
       */
      public long getScore() {
        return score_;
      }
      /**
       * <code>required int64 score = 3;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(long value) {
        bitField0_ |= 0x00000004;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 score = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          params_ = new com.google.protobuf.LazyStringArrayList(params_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return A list containing the params.
       */
      public com.google.protobuf.ProtocolStringList
          getParamsList() {
        return params_.getUnmodifiableView();
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public java.lang.String getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the params at the given index.
       */
      public com.google.protobuf.ByteString
          getParamsBytes(int index) {
        return params_.getByteString(index);
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param value The bytes of the params to add.
       * @return This builder for chaining.
       */
      public Builder addParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901)
    }

    // @@protoc_insertion_point(class_scope:crossRank.com.gzbz.protobuf.S2CR_UpdateRank_10901)
    private static final com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901();
    }

    public static com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2CR_UpdateRank_10901>
        PARSER = new com.google.protobuf.AbstractParser<S2CR_UpdateRank_10901>() {
      @java.lang.Override
      public S2CR_UpdateRank_10901 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CR_UpdateRank_10901(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2CR_UpdateRank_10901> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2CR_UpdateRank_10901> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.CrossRankMsg.S2CR_UpdateRank_10901 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CrossRank.proto\022\033crossRank.com.gzbz.pr" +
      "otobuf\032\nRank.proto\"W\n\025S2CR_UpdateRank_10" +
      "901\022\020\n\010moduleId\030\001 \002(\005\022\r\n\005value\030\002 \002(\005\022\r\n\005" +
      "score\030\003 \002(\003\022\016\n\006params\030\004 \003(\tB#\n\021com.gzbz." +
      "protobufB\014CrossRankMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gzbz.protobuf.RankMsg.getDescriptor(),
        });
    internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crossRank_com_gzbz_protobuf_S2CR_UpdateRank_10901_descriptor,
        new java.lang.String[] { "ModuleId", "Value", "Score", "Params", });
    com.gzbz.protobuf.RankMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
