// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Failure.proto

package com.gzbz.protobuf;

public final class FailureMsg {
  private FailureMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2C_Failure_101OrBuilder extends
      // @@protoc_insertion_point(interface_extends:failure.com.gzbz.protobuf.S2C_Failure_101)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 errorCode = 1;</code>
     * @return Whether the errorCode field is set.
     */
    boolean hasErrorCode();
    /**
     * <code>required int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    int getErrorCode();

    /**
     * <code>optional string errorStr = 2;</code>
     * @return Whether the errorStr field is set.
     */
    boolean hasErrorStr();
    /**
     * <code>optional string errorStr = 2;</code>
     * @return The errorStr.
     */
    java.lang.String getErrorStr();
    /**
     * <code>optional string errorStr = 2;</code>
     * @return The bytes for errorStr.
     */
    com.google.protobuf.ByteString
        getErrorStrBytes();
  }
  /**
   * Protobuf type {@code failure.com.gzbz.protobuf.S2C_Failure_101}
   */
  public  static final class S2C_Failure_101 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:failure.com.gzbz.protobuf.S2C_Failure_101)
      S2C_Failure_101OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_Failure_101.newBuilder() to construct.
    private S2C_Failure_101(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_Failure_101() {
      errorStr_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_Failure_101();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_Failure_101(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorStr_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.FailureMsg.internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.FailureMsg.internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.FailureMsg.S2C_Failure_101.class, com.gzbz.protobuf.FailureMsg.S2C_Failure_101.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>required int32 errorCode = 1;</code>
     * @return Whether the errorCode field is set.
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORSTR_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorStr_;
    /**
     * <code>optional string errorStr = 2;</code>
     * @return Whether the errorStr field is set.
     */
    public boolean hasErrorStr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string errorStr = 2;</code>
     * @return The errorStr.
     */
    public java.lang.String getErrorStr() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorStr = 2;</code>
     * @return The bytes for errorStr.
     */
    public com.google.protobuf.ByteString
        getErrorStrBytes() {
      java.lang.Object ref = errorStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrorCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorStr_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.FailureMsg.S2C_Failure_101)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.FailureMsg.S2C_Failure_101 other = (com.gzbz.protobuf.FailureMsg.S2C_Failure_101) obj;

      if (hasErrorCode() != other.hasErrorCode()) return false;
      if (hasErrorCode()) {
        if (getErrorCode()
            != other.getErrorCode()) return false;
      }
      if (hasErrorStr() != other.hasErrorStr()) return false;
      if (hasErrorStr()) {
        if (!getErrorStr()
            .equals(other.getErrorStr())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrorCode()) {
        hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode();
      }
      if (hasErrorStr()) {
        hash = (37 * hash) + ERRORSTR_FIELD_NUMBER;
        hash = (53 * hash) + getErrorStr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.FailureMsg.S2C_Failure_101 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code failure.com.gzbz.protobuf.S2C_Failure_101}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:failure.com.gzbz.protobuf.S2C_Failure_101)
        com.gzbz.protobuf.FailureMsg.S2C_Failure_101OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.FailureMsg.internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.FailureMsg.internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.FailureMsg.S2C_Failure_101.class, com.gzbz.protobuf.FailureMsg.S2C_Failure_101.Builder.class);
      }

      // Construct using com.gzbz.protobuf.FailureMsg.S2C_Failure_101.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.FailureMsg.internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FailureMsg.S2C_Failure_101 getDefaultInstanceForType() {
        return com.gzbz.protobuf.FailureMsg.S2C_Failure_101.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.FailureMsg.S2C_Failure_101 build() {
        com.gzbz.protobuf.FailureMsg.S2C_Failure_101 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FailureMsg.S2C_Failure_101 buildPartial() {
        com.gzbz.protobuf.FailureMsg.S2C_Failure_101 result = new com.gzbz.protobuf.FailureMsg.S2C_Failure_101(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errorCode_ = errorCode_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorStr_ = errorStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.FailureMsg.S2C_Failure_101) {
          return mergeFrom((com.gzbz.protobuf.FailureMsg.S2C_Failure_101)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.FailureMsg.S2C_Failure_101 other) {
        if (other == com.gzbz.protobuf.FailureMsg.S2C_Failure_101.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorStr()) {
          bitField0_ |= 0x00000002;
          errorStr_ = other.errorStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasErrorCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.FailureMsg.S2C_Failure_101 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.FailureMsg.S2C_Failure_101) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ ;
      /**
       * <code>required int32 errorCode = 1;</code>
       * @return Whether the errorCode field is set.
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorStr_ = "";
      /**
       * <code>optional string errorStr = 2;</code>
       * @return Whether the errorStr field is set.
       */
      public boolean hasErrorStr() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string errorStr = 2;</code>
       * @return The errorStr.
       */
      public java.lang.String getErrorStr() {
        java.lang.Object ref = errorStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorStr = 2;</code>
       * @return The bytes for errorStr.
       */
      public com.google.protobuf.ByteString
          getErrorStrBytes() {
        java.lang.Object ref = errorStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorStr = 2;</code>
       * @param value The errorStr to set.
       * @return This builder for chaining.
       */
      public Builder setErrorStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorStr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorStr_ = getDefaultInstance().getErrorStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorStr = 2;</code>
       * @param value The bytes for errorStr to set.
       * @return This builder for chaining.
       */
      public Builder setErrorStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorStr_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:failure.com.gzbz.protobuf.S2C_Failure_101)
    }

    // @@protoc_insertion_point(class_scope:failure.com.gzbz.protobuf.S2C_Failure_101)
    private static final com.gzbz.protobuf.FailureMsg.S2C_Failure_101 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.FailureMsg.S2C_Failure_101();
    }

    public static com.gzbz.protobuf.FailureMsg.S2C_Failure_101 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_Failure_101>
        PARSER = new com.google.protobuf.AbstractParser<S2C_Failure_101>() {
      @java.lang.Override
      public S2C_Failure_101 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_Failure_101(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_Failure_101> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_Failure_101> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.FailureMsg.S2C_Failure_101 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rFailure.proto\022\031failure.com.gzbz.protob" +
      "uf\"6\n\017S2C_Failure_101\022\021\n\terrorCode\030\001 \002(\005" +
      "\022\020\n\010errorStr\030\002 \001(\tB!\n\021com.gzbz.protobufB" +
      "\nFailureMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_failure_com_gzbz_protobuf_S2C_Failure_101_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
