// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignInFourteen.proto

package com.gzbz.protobuf;

public final class FourteenSignInMsg {
  private FourteenSignInMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_FourteenSignInSign_24201OrBuilder extends
      // @@protoc_insertion_point(interface_extends:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201}
   */
  public  static final class C2S_FourteenSignInSign_24201 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201)
      C2S_FourteenSignInSign_24201OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_FourteenSignInSign_24201.newBuilder() to construct.
    private C2S_FourteenSignInSign_24201(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_FourteenSignInSign_24201() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_FourteenSignInSign_24201();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_FourteenSignInSign_24201(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.class, com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 other = (com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201)
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.class, com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.Builder.class);
      }

      // Construct using com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 getDefaultInstanceForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 build() {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 buildPartial() {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 result = new com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201) {
          return mergeFrom((com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 other) {
        if (other == com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201)
    }

    // @@protoc_insertion_point(class_scope:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24201)
    private static final com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201();
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_FourteenSignInSign_24201>
        PARSER = new com.google.protobuf.AbstractParser<C2S_FourteenSignInSign_24201>() {
      @java.lang.Override
      public C2S_FourteenSignInSign_24201 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_FourteenSignInSign_24201(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_FourteenSignInSign_24201> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_FourteenSignInSign_24201> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24201 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_FourteenSignInSign_24202OrBuilder extends
      // @@protoc_insertion_point(interface_extends:fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ActDay = 1;</code>
     * @return Whether the actDay field is set.
     */
    boolean hasActDay();
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return The actDay.
     */
    int getActDay();

    /**
     * <code>required int32 loginDay = 2;</code>
     * @return Whether the loginDay field is set.
     */
    boolean hasLoginDay();
    /**
     * <code>required int32 loginDay = 2;</code>
     * @return The loginDay.
     */
    int getLoginDay();

    /**
     * <code>required int32 retroactiveNum = 3;</code>
     * @return Whether the retroactiveNum field is set.
     */
    boolean hasRetroactiveNum();
    /**
     * <code>required int32 retroactiveNum = 3;</code>
     * @return The retroactiveNum.
     */
    int getRetroactiveNum();

    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @return A list containing the gotDay.
     */
    java.util.List<java.lang.Integer> getGotDayList();
    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @return The count of gotDay.
     */
    int getGotDayCount();
    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @param index The index of the element to return.
     * @return The gotDay at the given index.
     */
    int getGotDay(int index);

    /**
     * <code>required int32 openServerDay = 5;</code>
     * @return Whether the openServerDay field is set.
     */
    boolean hasOpenServerDay();
    /**
     * <code>required int32 openServerDay = 5;</code>
     * @return The openServerDay.
     */
    int getOpenServerDay();

    /**
     * <code>required int32 todayGetRetroactiveNum = 6;</code>
     * @return Whether the todayGetRetroactiveNum field is set.
     */
    boolean hasTodayGetRetroactiveNum();
    /**
     * <code>required int32 todayGetRetroactiveNum = 6;</code>
     * @return The todayGetRetroactiveNum.
     */
    int getTodayGetRetroactiveNum();

    /**
     * <code>required int32 todayRecharge = 7;</code>
     * @return Whether the todayRecharge field is set.
     */
    boolean hasTodayRecharge();
    /**
     * <code>required int32 todayRecharge = 7;</code>
     * @return The todayRecharge.
     */
    int getTodayRecharge();
  }
  /**
   * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202}
   */
  public  static final class S2C_FourteenSignInSign_24202 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202)
      S2C_FourteenSignInSign_24202OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_FourteenSignInSign_24202.newBuilder() to construct.
    private S2C_FourteenSignInSign_24202(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_FourteenSignInSign_24202() {
      gotDay_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_FourteenSignInSign_24202();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_FourteenSignInSign_24202(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              actDay_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              loginDay_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              retroactiveNum_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                gotDay_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              gotDay_.addInt(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                gotDay_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                gotDay_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              openServerDay_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              todayGetRetroactiveNum_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              todayRecharge_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          gotDay_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.class, com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.Builder.class);
    }

    private int bitField0_;
    public static final int ACTDAY_FIELD_NUMBER = 1;
    private int actDay_;
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return Whether the actDay field is set.
     */
    public boolean hasActDay() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return The actDay.
     */
    public int getActDay() {
      return actDay_;
    }

    public static final int LOGINDAY_FIELD_NUMBER = 2;
    private int loginDay_;
    /**
     * <code>required int32 loginDay = 2;</code>
     * @return Whether the loginDay field is set.
     */
    public boolean hasLoginDay() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 loginDay = 2;</code>
     * @return The loginDay.
     */
    public int getLoginDay() {
      return loginDay_;
    }

    public static final int RETROACTIVENUM_FIELD_NUMBER = 3;
    private int retroactiveNum_;
    /**
     * <code>required int32 retroactiveNum = 3;</code>
     * @return Whether the retroactiveNum field is set.
     */
    public boolean hasRetroactiveNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 retroactiveNum = 3;</code>
     * @return The retroactiveNum.
     */
    public int getRetroactiveNum() {
      return retroactiveNum_;
    }

    public static final int GOTDAY_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList gotDay_;
    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @return A list containing the gotDay.
     */
    public java.util.List<java.lang.Integer>
        getGotDayList() {
      return gotDay_;
    }
    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @return The count of gotDay.
     */
    public int getGotDayCount() {
      return gotDay_.size();
    }
    /**
     * <code>repeated int32 gotDay = 4;</code>
     * @param index The index of the element to return.
     * @return The gotDay at the given index.
     */
    public int getGotDay(int index) {
      return gotDay_.getInt(index);
    }

    public static final int OPENSERVERDAY_FIELD_NUMBER = 5;
    private int openServerDay_;
    /**
     * <code>required int32 openServerDay = 5;</code>
     * @return Whether the openServerDay field is set.
     */
    public boolean hasOpenServerDay() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 openServerDay = 5;</code>
     * @return The openServerDay.
     */
    public int getOpenServerDay() {
      return openServerDay_;
    }

    public static final int TODAYGETRETROACTIVENUM_FIELD_NUMBER = 6;
    private int todayGetRetroactiveNum_;
    /**
     * <code>required int32 todayGetRetroactiveNum = 6;</code>
     * @return Whether the todayGetRetroactiveNum field is set.
     */
    public boolean hasTodayGetRetroactiveNum() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 todayGetRetroactiveNum = 6;</code>
     * @return The todayGetRetroactiveNum.
     */
    public int getTodayGetRetroactiveNum() {
      return todayGetRetroactiveNum_;
    }

    public static final int TODAYRECHARGE_FIELD_NUMBER = 7;
    private int todayRecharge_;
    /**
     * <code>required int32 todayRecharge = 7;</code>
     * @return Whether the todayRecharge field is set.
     */
    public boolean hasTodayRecharge() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 todayRecharge = 7;</code>
     * @return The todayRecharge.
     */
    public int getTodayRecharge() {
      return todayRecharge_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasActDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoginDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRetroactiveNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpenServerDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayGetRetroactiveNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayRecharge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, actDay_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, loginDay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, retroactiveNum_);
      }
      for (int i = 0; i < gotDay_.size(); i++) {
        output.writeInt32(4, gotDay_.getInt(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(5, openServerDay_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, todayGetRetroactiveNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(7, todayRecharge_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, actDay_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, loginDay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, retroactiveNum_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gotDay_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(gotDay_.getInt(i));
        }
        size += dataSize;
        size += 1 * getGotDayList().size();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, openServerDay_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, todayGetRetroactiveNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, todayRecharge_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 other = (com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202) obj;

      if (hasActDay() != other.hasActDay()) return false;
      if (hasActDay()) {
        if (getActDay()
            != other.getActDay()) return false;
      }
      if (hasLoginDay() != other.hasLoginDay()) return false;
      if (hasLoginDay()) {
        if (getLoginDay()
            != other.getLoginDay()) return false;
      }
      if (hasRetroactiveNum() != other.hasRetroactiveNum()) return false;
      if (hasRetroactiveNum()) {
        if (getRetroactiveNum()
            != other.getRetroactiveNum()) return false;
      }
      if (!getGotDayList()
          .equals(other.getGotDayList())) return false;
      if (hasOpenServerDay() != other.hasOpenServerDay()) return false;
      if (hasOpenServerDay()) {
        if (getOpenServerDay()
            != other.getOpenServerDay()) return false;
      }
      if (hasTodayGetRetroactiveNum() != other.hasTodayGetRetroactiveNum()) return false;
      if (hasTodayGetRetroactiveNum()) {
        if (getTodayGetRetroactiveNum()
            != other.getTodayGetRetroactiveNum()) return false;
      }
      if (hasTodayRecharge() != other.hasTodayRecharge()) return false;
      if (hasTodayRecharge()) {
        if (getTodayRecharge()
            != other.getTodayRecharge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasActDay()) {
        hash = (37 * hash) + ACTDAY_FIELD_NUMBER;
        hash = (53 * hash) + getActDay();
      }
      if (hasLoginDay()) {
        hash = (37 * hash) + LOGINDAY_FIELD_NUMBER;
        hash = (53 * hash) + getLoginDay();
      }
      if (hasRetroactiveNum()) {
        hash = (37 * hash) + RETROACTIVENUM_FIELD_NUMBER;
        hash = (53 * hash) + getRetroactiveNum();
      }
      if (getGotDayCount() > 0) {
        hash = (37 * hash) + GOTDAY_FIELD_NUMBER;
        hash = (53 * hash) + getGotDayList().hashCode();
      }
      if (hasOpenServerDay()) {
        hash = (37 * hash) + OPENSERVERDAY_FIELD_NUMBER;
        hash = (53 * hash) + getOpenServerDay();
      }
      if (hasTodayGetRetroactiveNum()) {
        hash = (37 * hash) + TODAYGETRETROACTIVENUM_FIELD_NUMBER;
        hash = (53 * hash) + getTodayGetRetroactiveNum();
      }
      if (hasTodayRecharge()) {
        hash = (37 * hash) + TODAYRECHARGE_FIELD_NUMBER;
        hash = (53 * hash) + getTodayRecharge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202)
        com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.class, com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.Builder.class);
      }

      // Construct using com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        actDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        loginDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        retroactiveNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gotDay_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        openServerDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        todayGetRetroactiveNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        todayRecharge_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 getDefaultInstanceForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 build() {
        com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 buildPartial() {
        com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 result = new com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.actDay_ = actDay_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.loginDay_ = loginDay_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.retroactiveNum_ = retroactiveNum_;
          to_bitField0_ |= 0x00000004;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          gotDay_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.gotDay_ = gotDay_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.openServerDay_ = openServerDay_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.todayGetRetroactiveNum_ = todayGetRetroactiveNum_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.todayRecharge_ = todayRecharge_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202) {
          return mergeFrom((com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 other) {
        if (other == com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202.getDefaultInstance()) return this;
        if (other.hasActDay()) {
          setActDay(other.getActDay());
        }
        if (other.hasLoginDay()) {
          setLoginDay(other.getLoginDay());
        }
        if (other.hasRetroactiveNum()) {
          setRetroactiveNum(other.getRetroactiveNum());
        }
        if (!other.gotDay_.isEmpty()) {
          if (gotDay_.isEmpty()) {
            gotDay_ = other.gotDay_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGotDayIsMutable();
            gotDay_.addAll(other.gotDay_);
          }
          onChanged();
        }
        if (other.hasOpenServerDay()) {
          setOpenServerDay(other.getOpenServerDay());
        }
        if (other.hasTodayGetRetroactiveNum()) {
          setTodayGetRetroactiveNum(other.getTodayGetRetroactiveNum());
        }
        if (other.hasTodayRecharge()) {
          setTodayRecharge(other.getTodayRecharge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasActDay()) {
          return false;
        }
        if (!hasLoginDay()) {
          return false;
        }
        if (!hasRetroactiveNum()) {
          return false;
        }
        if (!hasOpenServerDay()) {
          return false;
        }
        if (!hasTodayGetRetroactiveNum()) {
          return false;
        }
        if (!hasTodayRecharge()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int actDay_ ;
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return Whether the actDay field is set.
       */
      public boolean hasActDay() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return The actDay.
       */
      public int getActDay() {
        return actDay_;
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @param value The actDay to set.
       * @return This builder for chaining.
       */
      public Builder setActDay(int value) {
        bitField0_ |= 0x00000001;
        actDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActDay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actDay_ = 0;
        onChanged();
        return this;
      }

      private int loginDay_ ;
      /**
       * <code>required int32 loginDay = 2;</code>
       * @return Whether the loginDay field is set.
       */
      public boolean hasLoginDay() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 loginDay = 2;</code>
       * @return The loginDay.
       */
      public int getLoginDay() {
        return loginDay_;
      }
      /**
       * <code>required int32 loginDay = 2;</code>
       * @param value The loginDay to set.
       * @return This builder for chaining.
       */
      public Builder setLoginDay(int value) {
        bitField0_ |= 0x00000002;
        loginDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 loginDay = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginDay_ = 0;
        onChanged();
        return this;
      }

      private int retroactiveNum_ ;
      /**
       * <code>required int32 retroactiveNum = 3;</code>
       * @return Whether the retroactiveNum field is set.
       */
      public boolean hasRetroactiveNum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 retroactiveNum = 3;</code>
       * @return The retroactiveNum.
       */
      public int getRetroactiveNum() {
        return retroactiveNum_;
      }
      /**
       * <code>required int32 retroactiveNum = 3;</code>
       * @param value The retroactiveNum to set.
       * @return This builder for chaining.
       */
      public Builder setRetroactiveNum(int value) {
        bitField0_ |= 0x00000004;
        retroactiveNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retroactiveNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetroactiveNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        retroactiveNum_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList gotDay_ = emptyIntList();
      private void ensureGotDayIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          gotDay_ = mutableCopy(gotDay_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @return A list containing the gotDay.
       */
      public java.util.List<java.lang.Integer>
          getGotDayList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(gotDay_) : gotDay_;
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @return The count of gotDay.
       */
      public int getGotDayCount() {
        return gotDay_.size();
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @param index The index of the element to return.
       * @return The gotDay at the given index.
       */
      public int getGotDay(int index) {
        return gotDay_.getInt(index);
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @param index The index to set the value at.
       * @param value The gotDay to set.
       * @return This builder for chaining.
       */
      public Builder setGotDay(
          int index, int value) {
        ensureGotDayIsMutable();
        gotDay_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @param value The gotDay to add.
       * @return This builder for chaining.
       */
      public Builder addGotDay(int value) {
        ensureGotDayIsMutable();
        gotDay_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @param values The gotDay to add.
       * @return This builder for chaining.
       */
      public Builder addAllGotDay(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGotDayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gotDay_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gotDay = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGotDay() {
        gotDay_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private int openServerDay_ ;
      /**
       * <code>required int32 openServerDay = 5;</code>
       * @return Whether the openServerDay field is set.
       */
      public boolean hasOpenServerDay() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 openServerDay = 5;</code>
       * @return The openServerDay.
       */
      public int getOpenServerDay() {
        return openServerDay_;
      }
      /**
       * <code>required int32 openServerDay = 5;</code>
       * @param value The openServerDay to set.
       * @return This builder for chaining.
       */
      public Builder setOpenServerDay(int value) {
        bitField0_ |= 0x00000010;
        openServerDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 openServerDay = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpenServerDay() {
        bitField0_ = (bitField0_ & ~0x00000010);
        openServerDay_ = 0;
        onChanged();
        return this;
      }

      private int todayGetRetroactiveNum_ ;
      /**
       * <code>required int32 todayGetRetroactiveNum = 6;</code>
       * @return Whether the todayGetRetroactiveNum field is set.
       */
      public boolean hasTodayGetRetroactiveNum() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 todayGetRetroactiveNum = 6;</code>
       * @return The todayGetRetroactiveNum.
       */
      public int getTodayGetRetroactiveNum() {
        return todayGetRetroactiveNum_;
      }
      /**
       * <code>required int32 todayGetRetroactiveNum = 6;</code>
       * @param value The todayGetRetroactiveNum to set.
       * @return This builder for chaining.
       */
      public Builder setTodayGetRetroactiveNum(int value) {
        bitField0_ |= 0x00000020;
        todayGetRetroactiveNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayGetRetroactiveNum = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTodayGetRetroactiveNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        todayGetRetroactiveNum_ = 0;
        onChanged();
        return this;
      }

      private int todayRecharge_ ;
      /**
       * <code>required int32 todayRecharge = 7;</code>
       * @return Whether the todayRecharge field is set.
       */
      public boolean hasTodayRecharge() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required int32 todayRecharge = 7;</code>
       * @return The todayRecharge.
       */
      public int getTodayRecharge() {
        return todayRecharge_;
      }
      /**
       * <code>required int32 todayRecharge = 7;</code>
       * @param value The todayRecharge to set.
       * @return This builder for chaining.
       */
      public Builder setTodayRecharge(int value) {
        bitField0_ |= 0x00000040;
        todayRecharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayRecharge = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTodayRecharge() {
        bitField0_ = (bitField0_ & ~0x00000040);
        todayRecharge_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202)
    }

    // @@protoc_insertion_point(class_scope:fourteenSignIn.com.gzbz.protobuf.S2C_FourteenSignInSign_24202)
    private static final com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202();
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_FourteenSignInSign_24202>
        PARSER = new com.google.protobuf.AbstractParser<S2C_FourteenSignInSign_24202>() {
      @java.lang.Override
      public S2C_FourteenSignInSign_24202 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_FourteenSignInSign_24202(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_FourteenSignInSign_24202> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_FourteenSignInSign_24202> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.FourteenSignInMsg.S2C_FourteenSignInSign_24202 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_FourteenSignInSign_24203OrBuilder extends
      // @@protoc_insertion_point(interface_extends:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 signDay = 1;</code>
     * @return A list containing the signDay.
     */
    java.util.List<java.lang.Integer> getSignDayList();
    /**
     * <code>repeated int32 signDay = 1;</code>
     * @return The count of signDay.
     */
    int getSignDayCount();
    /**
     * <code>repeated int32 signDay = 1;</code>
     * @param index The index of the element to return.
     * @return The signDay at the given index.
     */
    int getSignDay(int index);
  }
  /**
   * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203}
   */
  public  static final class C2S_FourteenSignInSign_24203 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203)
      C2S_FourteenSignInSign_24203OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_FourteenSignInSign_24203.newBuilder() to construct.
    private C2S_FourteenSignInSign_24203(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_FourteenSignInSign_24203() {
      signDay_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_FourteenSignInSign_24203();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_FourteenSignInSign_24203(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                signDay_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              signDay_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                signDay_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                signDay_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          signDay_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.class, com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.Builder.class);
    }

    public static final int SIGNDAY_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList signDay_;
    /**
     * <code>repeated int32 signDay = 1;</code>
     * @return A list containing the signDay.
     */
    public java.util.List<java.lang.Integer>
        getSignDayList() {
      return signDay_;
    }
    /**
     * <code>repeated int32 signDay = 1;</code>
     * @return The count of signDay.
     */
    public int getSignDayCount() {
      return signDay_.size();
    }
    /**
     * <code>repeated int32 signDay = 1;</code>
     * @param index The index of the element to return.
     * @return The signDay at the given index.
     */
    public int getSignDay(int index) {
      return signDay_.getInt(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < signDay_.size(); i++) {
        output.writeInt32(1, signDay_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < signDay_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(signDay_.getInt(i));
        }
        size += dataSize;
        size += 1 * getSignDayList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 other = (com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203) obj;

      if (!getSignDayList()
          .equals(other.getSignDayList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSignDayCount() > 0) {
        hash = (37 * hash) + SIGNDAY_FIELD_NUMBER;
        hash = (53 * hash) + getSignDayList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203)
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.class, com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.Builder.class);
      }

      // Construct using com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signDay_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 getDefaultInstanceForType() {
        return com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 build() {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 buildPartial() {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 result = new com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          signDay_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.signDay_ = signDay_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203) {
          return mergeFrom((com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 other) {
        if (other == com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203.getDefaultInstance()) return this;
        if (!other.signDay_.isEmpty()) {
          if (signDay_.isEmpty()) {
            signDay_ = other.signDay_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSignDayIsMutable();
            signDay_.addAll(other.signDay_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList signDay_ = emptyIntList();
      private void ensureSignDayIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          signDay_ = mutableCopy(signDay_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @return A list containing the signDay.
       */
      public java.util.List<java.lang.Integer>
          getSignDayList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(signDay_) : signDay_;
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @return The count of signDay.
       */
      public int getSignDayCount() {
        return signDay_.size();
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @param index The index of the element to return.
       * @return The signDay at the given index.
       */
      public int getSignDay(int index) {
        return signDay_.getInt(index);
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @param index The index to set the value at.
       * @param value The signDay to set.
       * @return This builder for chaining.
       */
      public Builder setSignDay(
          int index, int value) {
        ensureSignDayIsMutable();
        signDay_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @param value The signDay to add.
       * @return This builder for chaining.
       */
      public Builder addSignDay(int value) {
        ensureSignDayIsMutable();
        signDay_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @param values The signDay to add.
       * @return This builder for chaining.
       */
      public Builder addAllSignDay(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSignDayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signDay_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 signDay = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignDay() {
        signDay_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203)
    }

    // @@protoc_insertion_point(class_scope:fourteenSignIn.com.gzbz.protobuf.C2S_FourteenSignInSign_24203)
    private static final com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203();
    }

    public static com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_FourteenSignInSign_24203>
        PARSER = new com.google.protobuf.AbstractParser<C2S_FourteenSignInSign_24203>() {
      @java.lang.Override
      public C2S_FourteenSignInSign_24203 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_FourteenSignInSign_24203(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_FourteenSignInSign_24203> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_FourteenSignInSign_24203> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.FourteenSignInMsg.C2S_FourteenSignInSign_24203 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SignInFourteen.proto\022 fourteenSignIn.c" +
      "om.gzbz.protobuf\032\014common.proto\"\036\n\034C2S_Fo" +
      "urteenSignInSign_24201\"\266\001\n\034S2C_FourteenS" +
      "ignInSign_24202\022\016\n\006ActDay\030\001 \002(\005\022\020\n\010login" +
      "Day\030\002 \002(\005\022\026\n\016retroactiveNum\030\003 \002(\005\022\016\n\006got" +
      "Day\030\004 \003(\005\022\025\n\ropenServerDay\030\005 \002(\005\022\036\n\026toda" +
      "yGetRetroactiveNum\030\006 \002(\005\022\025\n\rtodayRecharg" +
      "e\030\007 \002(\005\"/\n\034C2S_FourteenSignInSign_24203\022" +
      "\017\n\007signDay\030\001 \003(\005B(\n\021com.gzbz.protobufB\021F" +
      "ourteenSignInMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gzbz.protobuf.CommonMsg.getDescriptor(),
        });
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24201_descriptor,
        new java.lang.String[] { });
    internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fourteenSignIn_com_gzbz_protobuf_S2C_FourteenSignInSign_24202_descriptor,
        new java.lang.String[] { "ActDay", "LoginDay", "RetroactiveNum", "GotDay", "OpenServerDay", "TodayGetRetroactiveNum", "TodayRecharge", });
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fourteenSignIn_com_gzbz_protobuf_C2S_FourteenSignInSign_24203_descriptor,
        new java.lang.String[] { "SignDay", });
    com.gzbz.protobuf.CommonMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
