// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeroPromote.proto

package com.gzbz.protobuf;

public final class HeroPromoteMsg {
  private HeroPromoteMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_HeroPromoteInfo_18801OrBuilder extends
      // @@protoc_insertion_point(interface_extends:heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801}
   */
  public  static final class C2S_HeroPromoteInfo_18801 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801)
      C2S_HeroPromoteInfo_18801OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_HeroPromoteInfo_18801.newBuilder() to construct.
    private C2S_HeroPromoteInfo_18801(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_HeroPromoteInfo_18801() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_HeroPromoteInfo_18801();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_HeroPromoteInfo_18801(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.class, com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 other = (com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801)
        com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.class, com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.Builder.class);
      }

      // Construct using com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 getDefaultInstanceForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 build() {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 buildPartial() {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 result = new com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801) {
          return mergeFrom((com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 other) {
        if (other == com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801)
    }

    // @@protoc_insertion_point(class_scope:heroPromote.com.gzbz.protobuf.C2S_HeroPromoteInfo_18801)
    private static final com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801();
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_HeroPromoteInfo_18801>
        PARSER = new com.google.protobuf.AbstractParser<C2S_HeroPromoteInfo_18801>() {
      @java.lang.Override
      public C2S_HeroPromoteInfo_18801 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_HeroPromoteInfo_18801(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_HeroPromoteInfo_18801> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_HeroPromoteInfo_18801> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.HeroPromoteMsg.C2S_HeroPromoteInfo_18801 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_HeroPromoteInfo_18802OrBuilder extends
      // @@protoc_insertion_point(interface_extends:heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>required bool state = 1;</code>
     * @return The state.
     */
    boolean getState();

    /**
     * <code>optional int32 level = 2;</code>
     * @return Whether the level field is set.
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 2;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>optional int32 stage = 3;</code>
     * @return Whether the stage field is set.
     */
    boolean hasStage();
    /**
     * <code>optional int32 stage = 3;</code>
     * @return The stage.
     */
    int getStage();

    /**
     * <code>optional int32 levelLimit = 4;</code>
     * @return Whether the levelLimit field is set.
     */
    boolean hasLevelLimit();
    /**
     * <code>optional int32 levelLimit = 4;</code>
     * @return The levelLimit.
     */
    int getLevelLimit();
  }
  /**
   * Protobuf type {@code heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802}
   */
  public  static final class S2C_HeroPromoteInfo_18802 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802)
      S2C_HeroPromoteInfo_18802OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_HeroPromoteInfo_18802.newBuilder() to construct.
    private S2C_HeroPromoteInfo_18802(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_HeroPromoteInfo_18802() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_HeroPromoteInfo_18802();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_HeroPromoteInfo_18802(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              state_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stage_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              levelLimit_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.class, com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.Builder.class);
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private boolean state_;
    /**
     * <code>required bool state = 1;</code>
     * @return Whether the state field is set.
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bool state = 1;</code>
     * @return The state.
     */
    public boolean getState() {
      return state_;
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>optional int32 level = 2;</code>
     * @return Whether the level field is set.
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 level = 2;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }

    public static final int STAGE_FIELD_NUMBER = 3;
    private int stage_;
    /**
     * <code>optional int32 stage = 3;</code>
     * @return Whether the stage field is set.
     */
    public boolean hasStage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 stage = 3;</code>
     * @return The stage.
     */
    public int getStage() {
      return stage_;
    }

    public static final int LEVELLIMIT_FIELD_NUMBER = 4;
    private int levelLimit_;
    /**
     * <code>optional int32 levelLimit = 4;</code>
     * @return Whether the levelLimit field is set.
     */
    public boolean hasLevelLimit() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 levelLimit = 4;</code>
     * @return The levelLimit.
     */
    public int getLevelLimit() {
      return levelLimit_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, level_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, stage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, levelLimit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, stage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, levelLimit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 other = (com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (getState()
            != other.getState()) return false;
      }
      if (hasLevel() != other.hasLevel()) return false;
      if (hasLevel()) {
        if (getLevel()
            != other.getLevel()) return false;
      }
      if (hasStage() != other.hasStage()) return false;
      if (hasStage()) {
        if (getStage()
            != other.getStage()) return false;
      }
      if (hasLevelLimit() != other.hasLevelLimit()) return false;
      if (hasLevelLimit()) {
        if (getLevelLimit()
            != other.getLevelLimit()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getState());
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasStage()) {
        hash = (37 * hash) + STAGE_FIELD_NUMBER;
        hash = (53 * hash) + getStage();
      }
      if (hasLevelLimit()) {
        hash = (37 * hash) + LEVELLIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getLevelLimit();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802)
        com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.class, com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.Builder.class);
      }

      // Construct using com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        stage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        levelLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 getDefaultInstanceForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 build() {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 buildPartial() {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 result = new com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.state_ = state_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.level_ = level_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.stage_ = stage_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.levelLimit_ = levelLimit_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802) {
          return mergeFrom((com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 other) {
        if (other == com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasStage()) {
          setStage(other.getStage());
        }
        if (other.hasLevelLimit()) {
          setLevelLimit(other.getLevelLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasState()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean state_ ;
      /**
       * <code>required bool state = 1;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bool state = 1;</code>
       * @return The state.
       */
      public boolean getState() {
        return state_;
      }
      /**
       * <code>required bool state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(boolean value) {
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = false;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>optional int32 level = 2;</code>
       * @return Whether the level field is set.
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 level = 2;</code>
       * @return The level.
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 2;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }

      private int stage_ ;
      /**
       * <code>optional int32 stage = 3;</code>
       * @return Whether the stage field is set.
       */
      public boolean hasStage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 stage = 3;</code>
       * @return The stage.
       */
      public int getStage() {
        return stage_;
      }
      /**
       * <code>optional int32 stage = 3;</code>
       * @param value The stage to set.
       * @return This builder for chaining.
       */
      public Builder setStage(int value) {
        bitField0_ |= 0x00000004;
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 stage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stage_ = 0;
        onChanged();
        return this;
      }

      private int levelLimit_ ;
      /**
       * <code>optional int32 levelLimit = 4;</code>
       * @return Whether the levelLimit field is set.
       */
      public boolean hasLevelLimit() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 levelLimit = 4;</code>
       * @return The levelLimit.
       */
      public int getLevelLimit() {
        return levelLimit_;
      }
      /**
       * <code>optional int32 levelLimit = 4;</code>
       * @param value The levelLimit to set.
       * @return This builder for chaining.
       */
      public Builder setLevelLimit(int value) {
        bitField0_ |= 0x00000008;
        levelLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 levelLimit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevelLimit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        levelLimit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802)
    }

    // @@protoc_insertion_point(class_scope:heroPromote.com.gzbz.protobuf.S2C_HeroPromoteInfo_18802)
    private static final com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802();
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_HeroPromoteInfo_18802>
        PARSER = new com.google.protobuf.AbstractParser<S2C_HeroPromoteInfo_18802>() {
      @java.lang.Override
      public S2C_HeroPromoteInfo_18802 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_HeroPromoteInfo_18802(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_HeroPromoteInfo_18802> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_HeroPromoteInfo_18802> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.HeroPromoteMsg.S2C_HeroPromoteInfo_18802 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_Upgrade_18803OrBuilder extends
      // @@protoc_insertion_point(interface_extends:heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803}
   */
  public  static final class C2S_Upgrade_18803 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803)
      C2S_Upgrade_18803OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_Upgrade_18803.newBuilder() to construct.
    private C2S_Upgrade_18803(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_Upgrade_18803() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_Upgrade_18803();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_Upgrade_18803(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.class, com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 other = (com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803)
        com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.class, com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.Builder.class);
      }

      // Construct using com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 getDefaultInstanceForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 build() {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 buildPartial() {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 result = new com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803) {
          return mergeFrom((com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 other) {
        if (other == com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803)
    }

    // @@protoc_insertion_point(class_scope:heroPromote.com.gzbz.protobuf.C2S_Upgrade_18803)
    private static final com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803();
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_Upgrade_18803>
        PARSER = new com.google.protobuf.AbstractParser<C2S_Upgrade_18803>() {
      @java.lang.Override
      public C2S_Upgrade_18803 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_Upgrade_18803(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_Upgrade_18803> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_Upgrade_18803> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.HeroPromoteMsg.C2S_Upgrade_18803 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_Upgrade_18804OrBuilder extends
      // @@protoc_insertion_point(interface_extends:heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 level = 1;</code>
     * @return Whether the level field is set.
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 1;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>required int32 stage = 2;</code>
     * @return Whether the stage field is set.
     */
    boolean hasStage();
    /**
     * <code>required int32 stage = 2;</code>
     * @return The stage.
     */
    int getStage();
  }
  /**
   * Protobuf type {@code heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804}
   */
  public  static final class S2C_Upgrade_18804 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804)
      S2C_Upgrade_18804OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_Upgrade_18804.newBuilder() to construct.
    private S2C_Upgrade_18804(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_Upgrade_18804() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_Upgrade_18804();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_Upgrade_18804(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stage_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.class, com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.Builder.class);
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>required int32 level = 1;</code>
     * @return Whether the level field is set.
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 level = 1;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }

    public static final int STAGE_FIELD_NUMBER = 2;
    private int stage_;
    /**
     * <code>required int32 stage = 2;</code>
     * @return Whether the stage field is set.
     */
    public boolean hasStage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 stage = 2;</code>
     * @return The stage.
     */
    public int getStage() {
      return stage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, level_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, stage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 other = (com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804) obj;

      if (hasLevel() != other.hasLevel()) return false;
      if (hasLevel()) {
        if (getLevel()
            != other.getLevel()) return false;
      }
      if (hasStage() != other.hasStage()) return false;
      if (hasStage()) {
        if (getStage()
            != other.getStage()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasStage()) {
        hash = (37 * hash) + STAGE_FIELD_NUMBER;
        hash = (53 * hash) + getStage();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804)
        com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.class, com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.Builder.class);
      }

      // Construct using com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 getDefaultInstanceForType() {
        return com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 build() {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 buildPartial() {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 result = new com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.level_ = level_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stage_ = stage_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804) {
          return mergeFrom((com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 other) {
        if (other == com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasStage()) {
          setStage(other.getStage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasLevel()) {
          return false;
        }
        if (!hasStage()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int level_ ;
      /**
       * <code>required int32 level = 1;</code>
       * @return Whether the level field is set.
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 level = 1;</code>
       * @return The level.
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 1;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      private int stage_ ;
      /**
       * <code>required int32 stage = 2;</code>
       * @return Whether the stage field is set.
       */
      public boolean hasStage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 stage = 2;</code>
       * @return The stage.
       */
      public int getStage() {
        return stage_;
      }
      /**
       * <code>required int32 stage = 2;</code>
       * @param value The stage to set.
       * @return This builder for chaining.
       */
      public Builder setStage(int value) {
        bitField0_ |= 0x00000002;
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stage_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804)
    }

    // @@protoc_insertion_point(class_scope:heroPromote.com.gzbz.protobuf.S2C_Upgrade_18804)
    private static final com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804();
    }

    public static com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_Upgrade_18804>
        PARSER = new com.google.protobuf.AbstractParser<S2C_Upgrade_18804>() {
      @java.lang.Override
      public S2C_Upgrade_18804 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_Upgrade_18804(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_Upgrade_18804> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_Upgrade_18804> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.HeroPromoteMsg.S2C_Upgrade_18804 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HeroPromote.proto\022\035heroPromote.com.gzb" +
      "z.protobuf\"\033\n\031C2S_HeroPromoteInfo_18801\"" +
      "\\\n\031S2C_HeroPromoteInfo_18802\022\r\n\005state\030\001 " +
      "\002(\010\022\r\n\005level\030\002 \001(\005\022\r\n\005stage\030\003 \001(\005\022\022\n\nlev" +
      "elLimit\030\004 \001(\005\"\023\n\021C2S_Upgrade_18803\"1\n\021S2" +
      "C_Upgrade_18804\022\r\n\005level\030\001 \002(\005\022\r\n\005stage\030" +
      "\002 \002(\005B%\n\021com.gzbz.protobufB\016HeroPromoteM" +
      "sgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heroPromote_com_gzbz_protobuf_C2S_HeroPromoteInfo_18801_descriptor,
        new java.lang.String[] { });
    internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heroPromote_com_gzbz_protobuf_S2C_HeroPromoteInfo_18802_descriptor,
        new java.lang.String[] { "State", "Level", "Stage", "LevelLimit", });
    internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heroPromote_com_gzbz_protobuf_C2S_Upgrade_18803_descriptor,
        new java.lang.String[] { });
    internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heroPromote_com_gzbz_protobuf_S2C_Upgrade_18804_descriptor,
        new java.lang.String[] { "Level", "Stage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
