// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeroGodTrial.proto

package com.gzbz.protobuf;

public final class HeroGodTrialMsg {
  private HeroGodTrialMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HeroGodTrial.proto\022\036heroGodTrial.com.g" +
      "zbz.protobuf\032\014common.proto\032\021BattleDaily." +
      "proto\032\nRank.protoB&\n\021com.gzbz.protobufB\017" +
      "HeroGodTrialMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gzbz.protobuf.CommonMsg.getDescriptor(),
          com.gzbz.protobuf.BattleDailyMsg.getDescriptor(),
          com.gzbz.protobuf.RankMsg.getDescriptor(),
        });
    com.gzbz.protobuf.CommonMsg.getDescriptor();
    com.gzbz.protobuf.BattleDailyMsg.getDescriptor();
    com.gzbz.protobuf.RankMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
