// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewYearGift.proto

package com.gzbz.protobuf;

public final class NewYearGiftMsg {
  private NewYearGiftMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_ActivityInfo_18201OrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201}
   */
  public  static final class C2S_ActivityInfo_18201 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201)
      C2S_ActivityInfo_18201OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_ActivityInfo_18201.newBuilder() to construct.
    private C2S_ActivityInfo_18201(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_ActivityInfo_18201() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_ActivityInfo_18201();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_ActivityInfo_18201(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.class, com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 other = (com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201)
        com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.class, com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.Builder.class);
      }

      // Construct using com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 getDefaultInstanceForType() {
        return com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 build() {
        com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 buildPartial() {
        com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 result = new com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201) {
          return mergeFrom((com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 other) {
        if (other == com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201)
    }

    // @@protoc_insertion_point(class_scope:NewYearGift.com.gzbz.protobuf.C2S_ActivityInfo_18201)
    private static final com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201();
    }

    public static com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_ActivityInfo_18201>
        PARSER = new com.google.protobuf.AbstractParser<C2S_ActivityInfo_18201>() {
      @java.lang.Override
      public C2S_ActivityInfo_18201 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_ActivityInfo_18201(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_ActivityInfo_18201> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_ActivityInfo_18201> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.NewYearGiftMsg.C2S_ActivityInfo_18201 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_ActivityInfo_18202OrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 newYearGiftPlayerLv = 1;</code>
     * @return Whether the newYearGiftPlayerLv field is set.
     */
    boolean hasNewYearGiftPlayerLv();
    /**
     * <code>required int32 newYearGiftPlayerLv = 1;</code>
     * @return The newYearGiftPlayerLv.
     */
    int getNewYearGiftPlayerLv();

    /**
     * <code>required int32 openDay = 2;</code>
     * @return Whether the openDay field is set.
     */
    boolean hasOpenDay();
    /**
     * <code>required int32 openDay = 2;</code>
     * @return The openDay.
     */
    int getOpenDay();

    /**
     * <code>required bool isResetDaily = 3;</code>
     * @return Whether the isResetDaily field is set.
     */
    boolean hasIsResetDaily();
    /**
     * <code>required bool isResetDaily = 3;</code>
     * @return The isResetDaily.
     */
    boolean getIsResetDaily();
  }
  /**
   * Protobuf type {@code NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202}
   */
  public  static final class S2C_ActivityInfo_18202 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202)
      S2C_ActivityInfo_18202OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_ActivityInfo_18202.newBuilder() to construct.
    private S2C_ActivityInfo_18202(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_ActivityInfo_18202() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_ActivityInfo_18202();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_ActivityInfo_18202(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              newYearGiftPlayerLv_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              openDay_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isResetDaily_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.class, com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.Builder.class);
    }

    private int bitField0_;
    public static final int NEWYEARGIFTPLAYERLV_FIELD_NUMBER = 1;
    private int newYearGiftPlayerLv_;
    /**
     * <code>required int32 newYearGiftPlayerLv = 1;</code>
     * @return Whether the newYearGiftPlayerLv field is set.
     */
    public boolean hasNewYearGiftPlayerLv() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 newYearGiftPlayerLv = 1;</code>
     * @return The newYearGiftPlayerLv.
     */
    public int getNewYearGiftPlayerLv() {
      return newYearGiftPlayerLv_;
    }

    public static final int OPENDAY_FIELD_NUMBER = 2;
    private int openDay_;
    /**
     * <code>required int32 openDay = 2;</code>
     * @return Whether the openDay field is set.
     */
    public boolean hasOpenDay() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 openDay = 2;</code>
     * @return The openDay.
     */
    public int getOpenDay() {
      return openDay_;
    }

    public static final int ISRESETDAILY_FIELD_NUMBER = 3;
    private boolean isResetDaily_;
    /**
     * <code>required bool isResetDaily = 3;</code>
     * @return Whether the isResetDaily field is set.
     */
    public boolean hasIsResetDaily() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool isResetDaily = 3;</code>
     * @return The isResetDaily.
     */
    public boolean getIsResetDaily() {
      return isResetDaily_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNewYearGiftPlayerLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpenDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsResetDaily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, newYearGiftPlayerLv_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, openDay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, isResetDaily_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, newYearGiftPlayerLv_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, openDay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isResetDaily_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 other = (com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202) obj;

      if (hasNewYearGiftPlayerLv() != other.hasNewYearGiftPlayerLv()) return false;
      if (hasNewYearGiftPlayerLv()) {
        if (getNewYearGiftPlayerLv()
            != other.getNewYearGiftPlayerLv()) return false;
      }
      if (hasOpenDay() != other.hasOpenDay()) return false;
      if (hasOpenDay()) {
        if (getOpenDay()
            != other.getOpenDay()) return false;
      }
      if (hasIsResetDaily() != other.hasIsResetDaily()) return false;
      if (hasIsResetDaily()) {
        if (getIsResetDaily()
            != other.getIsResetDaily()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNewYearGiftPlayerLv()) {
        hash = (37 * hash) + NEWYEARGIFTPLAYERLV_FIELD_NUMBER;
        hash = (53 * hash) + getNewYearGiftPlayerLv();
      }
      if (hasOpenDay()) {
        hash = (37 * hash) + OPENDAY_FIELD_NUMBER;
        hash = (53 * hash) + getOpenDay();
      }
      if (hasIsResetDaily()) {
        hash = (37 * hash) + ISRESETDAILY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsResetDaily());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202)
        com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.class, com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.Builder.class);
      }

      // Construct using com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        newYearGiftPlayerLv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        openDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isResetDaily_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.NewYearGiftMsg.internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 getDefaultInstanceForType() {
        return com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 build() {
        com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 buildPartial() {
        com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 result = new com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.newYearGiftPlayerLv_ = newYearGiftPlayerLv_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.openDay_ = openDay_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isResetDaily_ = isResetDaily_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202) {
          return mergeFrom((com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 other) {
        if (other == com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202.getDefaultInstance()) return this;
        if (other.hasNewYearGiftPlayerLv()) {
          setNewYearGiftPlayerLv(other.getNewYearGiftPlayerLv());
        }
        if (other.hasOpenDay()) {
          setOpenDay(other.getOpenDay());
        }
        if (other.hasIsResetDaily()) {
          setIsResetDaily(other.getIsResetDaily());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasNewYearGiftPlayerLv()) {
          return false;
        }
        if (!hasOpenDay()) {
          return false;
        }
        if (!hasIsResetDaily()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int newYearGiftPlayerLv_ ;
      /**
       * <code>required int32 newYearGiftPlayerLv = 1;</code>
       * @return Whether the newYearGiftPlayerLv field is set.
       */
      public boolean hasNewYearGiftPlayerLv() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 newYearGiftPlayerLv = 1;</code>
       * @return The newYearGiftPlayerLv.
       */
      public int getNewYearGiftPlayerLv() {
        return newYearGiftPlayerLv_;
      }
      /**
       * <code>required int32 newYearGiftPlayerLv = 1;</code>
       * @param value The newYearGiftPlayerLv to set.
       * @return This builder for chaining.
       */
      public Builder setNewYearGiftPlayerLv(int value) {
        bitField0_ |= 0x00000001;
        newYearGiftPlayerLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 newYearGiftPlayerLv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewYearGiftPlayerLv() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newYearGiftPlayerLv_ = 0;
        onChanged();
        return this;
      }

      private int openDay_ ;
      /**
       * <code>required int32 openDay = 2;</code>
       * @return Whether the openDay field is set.
       */
      public boolean hasOpenDay() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 openDay = 2;</code>
       * @return The openDay.
       */
      public int getOpenDay() {
        return openDay_;
      }
      /**
       * <code>required int32 openDay = 2;</code>
       * @param value The openDay to set.
       * @return This builder for chaining.
       */
      public Builder setOpenDay(int value) {
        bitField0_ |= 0x00000002;
        openDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 openDay = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpenDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        openDay_ = 0;
        onChanged();
        return this;
      }

      private boolean isResetDaily_ ;
      /**
       * <code>required bool isResetDaily = 3;</code>
       * @return Whether the isResetDaily field is set.
       */
      public boolean hasIsResetDaily() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bool isResetDaily = 3;</code>
       * @return The isResetDaily.
       */
      public boolean getIsResetDaily() {
        return isResetDaily_;
      }
      /**
       * <code>required bool isResetDaily = 3;</code>
       * @param value The isResetDaily to set.
       * @return This builder for chaining.
       */
      public Builder setIsResetDaily(boolean value) {
        bitField0_ |= 0x00000004;
        isResetDaily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isResetDaily = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsResetDaily() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isResetDaily_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202)
    }

    // @@protoc_insertion_point(class_scope:NewYearGift.com.gzbz.protobuf.S2C_ActivityInfo_18202)
    private static final com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202();
    }

    public static com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_ActivityInfo_18202>
        PARSER = new com.google.protobuf.AbstractParser<S2C_ActivityInfo_18202>() {
      @java.lang.Override
      public S2C_ActivityInfo_18202 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_ActivityInfo_18202(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_ActivityInfo_18202> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_ActivityInfo_18202> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.NewYearGiftMsg.S2C_ActivityInfo_18202 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021NewYearGift.proto\022\035NewYearGift.com.gzb" +
      "z.protobuf\"\030\n\026C2S_ActivityInfo_18201\"\\\n\026" +
      "S2C_ActivityInfo_18202\022\033\n\023newYearGiftPla" +
      "yerLv\030\001 \002(\005\022\017\n\007openDay\030\002 \002(\005\022\024\n\014isResetD" +
      "aily\030\003 \002(\010B%\n\021com.gzbz.protobufB\016NewYear" +
      "GiftMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewYearGift_com_gzbz_protobuf_C2S_ActivityInfo_18201_descriptor,
        new java.lang.String[] { });
    internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewYearGift_com_gzbz_protobuf_S2C_ActivityInfo_18202_descriptor,
        new java.lang.String[] { "NewYearGiftPlayerLv", "OpenDay", "IsResetDaily", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
