// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkersReward.proto

package com.gzbz.protobuf;

public final class WorkersDayRewardMsg {
  private WorkersDayRewardMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_GetWorkersDayRewardInfo_19701OrBuilder extends
      // @@protoc_insertion_point(interface_extends:workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701}
   */
  public  static final class C2S_GetWorkersDayRewardInfo_19701 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701)
      C2S_GetWorkersDayRewardInfo_19701OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_GetWorkersDayRewardInfo_19701.newBuilder() to construct.
    private C2S_GetWorkersDayRewardInfo_19701(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_GetWorkersDayRewardInfo_19701() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_GetWorkersDayRewardInfo_19701();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_GetWorkersDayRewardInfo_19701(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.class, com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 other = (com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701)
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.class, com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.Builder.class);
      }

      // Construct using com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 getDefaultInstanceForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 build() {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 buildPartial() {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 result = new com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701) {
          return mergeFrom((com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 other) {
        if (other == com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701)
    }

    // @@protoc_insertion_point(class_scope:workersDayReward.com.gzbz.protobuf.C2S_GetWorkersDayRewardInfo_19701)
    private static final com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701();
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_GetWorkersDayRewardInfo_19701>
        PARSER = new com.google.protobuf.AbstractParser<C2S_GetWorkersDayRewardInfo_19701>() {
      @java.lang.Override
      public C2S_GetWorkersDayRewardInfo_19701 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_GetWorkersDayRewardInfo_19701(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_GetWorkersDayRewardInfo_19701> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_GetWorkersDayRewardInfo_19701> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_GetWorkersDayRewardInfo_19701 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_GetWorkersDayRewardInfo_19702OrBuilder extends
      // @@protoc_insertion_point(interface_extends:workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool isReceiveReward = 1;</code>
     * @return Whether the isReceiveReward field is set.
     */
    boolean hasIsReceiveReward();
    /**
     * <code>required bool isReceiveReward = 1;</code>
     * @return The isReceiveReward.
     */
    boolean getIsReceiveReward();
  }
  /**
   * Protobuf type {@code workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702}
   */
  public  static final class S2C_GetWorkersDayRewardInfo_19702 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702)
      S2C_GetWorkersDayRewardInfo_19702OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_GetWorkersDayRewardInfo_19702.newBuilder() to construct.
    private S2C_GetWorkersDayRewardInfo_19702(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_GetWorkersDayRewardInfo_19702() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_GetWorkersDayRewardInfo_19702();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_GetWorkersDayRewardInfo_19702(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isReceiveReward_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.class, com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.Builder.class);
    }

    private int bitField0_;
    public static final int ISRECEIVEREWARD_FIELD_NUMBER = 1;
    private boolean isReceiveReward_;
    /**
     * <code>required bool isReceiveReward = 1;</code>
     * @return Whether the isReceiveReward field is set.
     */
    public boolean hasIsReceiveReward() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bool isReceiveReward = 1;</code>
     * @return The isReceiveReward.
     */
    public boolean getIsReceiveReward() {
      return isReceiveReward_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsReceiveReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isReceiveReward_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isReceiveReward_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 other = (com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702) obj;

      if (hasIsReceiveReward() != other.hasIsReceiveReward()) return false;
      if (hasIsReceiveReward()) {
        if (getIsReceiveReward()
            != other.getIsReceiveReward()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsReceiveReward()) {
        hash = (37 * hash) + ISRECEIVEREWARD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsReceiveReward());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702)
        com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.class, com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.Builder.class);
      }

      // Construct using com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isReceiveReward_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 getDefaultInstanceForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 build() {
        com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 buildPartial() {
        com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 result = new com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isReceiveReward_ = isReceiveReward_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702) {
          return mergeFrom((com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 other) {
        if (other == com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702.getDefaultInstance()) return this;
        if (other.hasIsReceiveReward()) {
          setIsReceiveReward(other.getIsReceiveReward());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIsReceiveReward()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isReceiveReward_ ;
      /**
       * <code>required bool isReceiveReward = 1;</code>
       * @return Whether the isReceiveReward field is set.
       */
      public boolean hasIsReceiveReward() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bool isReceiveReward = 1;</code>
       * @return The isReceiveReward.
       */
      public boolean getIsReceiveReward() {
        return isReceiveReward_;
      }
      /**
       * <code>required bool isReceiveReward = 1;</code>
       * @param value The isReceiveReward to set.
       * @return This builder for chaining.
       */
      public Builder setIsReceiveReward(boolean value) {
        bitField0_ |= 0x00000001;
        isReceiveReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isReceiveReward = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsReceiveReward() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isReceiveReward_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702)
    }

    // @@protoc_insertion_point(class_scope:workersDayReward.com.gzbz.protobuf.S2C_GetWorkersDayRewardInfo_19702)
    private static final com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702();
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_GetWorkersDayRewardInfo_19702>
        PARSER = new com.google.protobuf.AbstractParser<S2C_GetWorkersDayRewardInfo_19702>() {
      @java.lang.Override
      public S2C_GetWorkersDayRewardInfo_19702 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_GetWorkersDayRewardInfo_19702(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_GetWorkersDayRewardInfo_19702> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_GetWorkersDayRewardInfo_19702> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.WorkersDayRewardMsg.S2C_GetWorkersDayRewardInfo_19702 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_ReceiveWorkersDayReward_19703OrBuilder extends
      // @@protoc_insertion_point(interface_extends:workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703}
   */
  public  static final class C2S_ReceiveWorkersDayReward_19703 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703)
      C2S_ReceiveWorkersDayReward_19703OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_ReceiveWorkersDayReward_19703.newBuilder() to construct.
    private C2S_ReceiveWorkersDayReward_19703(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_ReceiveWorkersDayReward_19703() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_ReceiveWorkersDayReward_19703();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_ReceiveWorkersDayReward_19703(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.class, com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 other = (com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703)
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.class, com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.Builder.class);
      }

      // Construct using com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 getDefaultInstanceForType() {
        return com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 build() {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 buildPartial() {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 result = new com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703) {
          return mergeFrom((com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 other) {
        if (other == com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703)
    }

    // @@protoc_insertion_point(class_scope:workersDayReward.com.gzbz.protobuf.C2S_ReceiveWorkersDayReward_19703)
    private static final com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703();
    }

    public static com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_ReceiveWorkersDayReward_19703>
        PARSER = new com.google.protobuf.AbstractParser<C2S_ReceiveWorkersDayReward_19703>() {
      @java.lang.Override
      public C2S_ReceiveWorkersDayReward_19703 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_ReceiveWorkersDayReward_19703(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_ReceiveWorkersDayReward_19703> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_ReceiveWorkersDayReward_19703> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.WorkersDayRewardMsg.C2S_ReceiveWorkersDayReward_19703 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WorkersReward.proto\022\"workersDayReward." +
      "com.gzbz.protobuf\"#\n!C2S_GetWorkersDayRe" +
      "wardInfo_19701\"<\n!S2C_GetWorkersDayRewar" +
      "dInfo_19702\022\027\n\017isReceiveReward\030\001 \002(\010\"#\n!" +
      "C2S_ReceiveWorkersDayReward_19703B*\n\021com" +
      ".gzbz.protobufB\023WorkersDayRewardMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workersDayReward_com_gzbz_protobuf_C2S_GetWorkersDayRewardInfo_19701_descriptor,
        new java.lang.String[] { });
    internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workersDayReward_com_gzbz_protobuf_S2C_GetWorkersDayRewardInfo_19702_descriptor,
        new java.lang.String[] { "IsReceiveReward", });
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workersDayReward_com_gzbz_protobuf_C2S_ReceiveWorkersDayReward_19703_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
