// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZhenYu.proto

package com.gzbz.protobuf;

public final class ZhenYuMsg {
  private ZhenYuMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_ShopInfo_29001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001}
   */
  public  static final class C2S_ShopInfo_29001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001)
      C2S_ShopInfo_29001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_ShopInfo_29001.newBuilder() to construct.
    private C2S_ShopInfo_29001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_ShopInfo_29001() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_ShopInfo_29001();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_ShopInfo_29001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.class, com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 other = (com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001)
        com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.class, com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.Builder.class);
      }

      // Construct using com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 getDefaultInstanceForType() {
        return com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 build() {
        com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 buildPartial() {
        com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 result = new com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001) {
          return mergeFrom((com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 other) {
        if (other == com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001)
    }

    // @@protoc_insertion_point(class_scope:zhenYu.com.gzbz.protobuf.C2S_ShopInfo_29001)
    private static final com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001();
    }

    public static com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_ShopInfo_29001>
        PARSER = new com.google.protobuf.AbstractParser<C2S_ShopInfo_29001>() {
      @java.lang.Override
      public C2S_ShopInfo_29001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_ShopInfo_29001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_ShopInfo_29001> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_ShopInfo_29001> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.ZhenYuMsg.C2S_ShopInfo_29001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_ShopInfo_29002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 ActDay = 1;</code>
     * @return Whether the actDay field is set.
     */
    boolean hasActDay();
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return The actDay.
     */
    int getActDay();

    /**
     * <code>required int32 openServerDay = 2;</code>
     * @return Whether the openServerDay field is set.
     */
    boolean hasOpenServerDay();
    /**
     * <code>required int32 openServerDay = 2;</code>
     * @return The openServerDay.
     */
    int getOpenServerDay();

    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo> 
        getShopList();
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    com.gzbz.protobuf.ZhenYuMsg.ShopInfo getShop(int index);
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    int getShopCount();
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    java.util.List<? extends com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder> 
        getShopOrBuilderList();
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder getShopOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002}
   */
  public  static final class S2C_ShopInfo_29002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002)
      S2C_ShopInfo_29002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_ShopInfo_29002.newBuilder() to construct.
    private S2C_ShopInfo_29002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_ShopInfo_29002() {
      shop_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C_ShopInfo_29002();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_ShopInfo_29002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              actDay_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              openServerDay_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                shop_ = new java.util.ArrayList<com.gzbz.protobuf.ZhenYuMsg.ShopInfo>();
                mutable_bitField0_ |= 0x00000004;
              }
              shop_.add(
                  input.readMessage(com.gzbz.protobuf.ZhenYuMsg.ShopInfo.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          shop_ = java.util.Collections.unmodifiableList(shop_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.class, com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.Builder.class);
    }

    private int bitField0_;
    public static final int ACTDAY_FIELD_NUMBER = 1;
    private int actDay_;
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return Whether the actDay field is set.
     */
    public boolean hasActDay() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 ActDay = 1;</code>
     * @return The actDay.
     */
    public int getActDay() {
      return actDay_;
    }

    public static final int OPENSERVERDAY_FIELD_NUMBER = 2;
    private int openServerDay_;
    /**
     * <code>required int32 openServerDay = 2;</code>
     * @return Whether the openServerDay field is set.
     */
    public boolean hasOpenServerDay() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 openServerDay = 2;</code>
     * @return The openServerDay.
     */
    public int getOpenServerDay() {
      return openServerDay_;
    }

    public static final int SHOP_FIELD_NUMBER = 3;
    private java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo> shop_;
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    public java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo> getShopList() {
      return shop_;
    }
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    public java.util.List<? extends com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder> 
        getShopOrBuilderList() {
      return shop_;
    }
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    public int getShopCount() {
      return shop_.size();
    }
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    public com.gzbz.protobuf.ZhenYuMsg.ShopInfo getShop(int index) {
      return shop_.get(index);
    }
    /**
     * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
     */
    public com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder getShopOrBuilder(
        int index) {
      return shop_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasActDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpenServerDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getShopCount(); i++) {
        if (!getShop(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, actDay_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, openServerDay_);
      }
      for (int i = 0; i < shop_.size(); i++) {
        output.writeMessage(3, shop_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, actDay_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, openServerDay_);
      }
      for (int i = 0; i < shop_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, shop_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 other = (com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002) obj;

      if (hasActDay() != other.hasActDay()) return false;
      if (hasActDay()) {
        if (getActDay()
            != other.getActDay()) return false;
      }
      if (hasOpenServerDay() != other.hasOpenServerDay()) return false;
      if (hasOpenServerDay()) {
        if (getOpenServerDay()
            != other.getOpenServerDay()) return false;
      }
      if (!getShopList()
          .equals(other.getShopList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasActDay()) {
        hash = (37 * hash) + ACTDAY_FIELD_NUMBER;
        hash = (53 * hash) + getActDay();
      }
      if (hasOpenServerDay()) {
        hash = (37 * hash) + OPENSERVERDAY_FIELD_NUMBER;
        hash = (53 * hash) + getOpenServerDay();
      }
      if (getShopCount() > 0) {
        hash = (37 * hash) + SHOP_FIELD_NUMBER;
        hash = (53 * hash) + getShopList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002)
        com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.class, com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.Builder.class);
      }

      // Construct using com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getShopFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        actDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        openServerDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (shopBuilder_ == null) {
          shop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          shopBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 getDefaultInstanceForType() {
        return com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 build() {
        com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 buildPartial() {
        com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 result = new com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.actDay_ = actDay_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.openServerDay_ = openServerDay_;
          to_bitField0_ |= 0x00000002;
        }
        if (shopBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            shop_ = java.util.Collections.unmodifiableList(shop_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.shop_ = shop_;
        } else {
          result.shop_ = shopBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002) {
          return mergeFrom((com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 other) {
        if (other == com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002.getDefaultInstance()) return this;
        if (other.hasActDay()) {
          setActDay(other.getActDay());
        }
        if (other.hasOpenServerDay()) {
          setOpenServerDay(other.getOpenServerDay());
        }
        if (shopBuilder_ == null) {
          if (!other.shop_.isEmpty()) {
            if (shop_.isEmpty()) {
              shop_ = other.shop_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureShopIsMutable();
              shop_.addAll(other.shop_);
            }
            onChanged();
          }
        } else {
          if (!other.shop_.isEmpty()) {
            if (shopBuilder_.isEmpty()) {
              shopBuilder_.dispose();
              shopBuilder_ = null;
              shop_ = other.shop_;
              bitField0_ = (bitField0_ & ~0x00000004);
              shopBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getShopFieldBuilder() : null;
            } else {
              shopBuilder_.addAllMessages(other.shop_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasActDay()) {
          return false;
        }
        if (!hasOpenServerDay()) {
          return false;
        }
        for (int i = 0; i < getShopCount(); i++) {
          if (!getShop(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int actDay_ ;
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return Whether the actDay field is set.
       */
      public boolean hasActDay() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return The actDay.
       */
      public int getActDay() {
        return actDay_;
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @param value The actDay to set.
       * @return This builder for chaining.
       */
      public Builder setActDay(int value) {
        bitField0_ |= 0x00000001;
        actDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ActDay = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActDay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actDay_ = 0;
        onChanged();
        return this;
      }

      private int openServerDay_ ;
      /**
       * <code>required int32 openServerDay = 2;</code>
       * @return Whether the openServerDay field is set.
       */
      public boolean hasOpenServerDay() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 openServerDay = 2;</code>
       * @return The openServerDay.
       */
      public int getOpenServerDay() {
        return openServerDay_;
      }
      /**
       * <code>required int32 openServerDay = 2;</code>
       * @param value The openServerDay to set.
       * @return This builder for chaining.
       */
      public Builder setOpenServerDay(int value) {
        bitField0_ |= 0x00000002;
        openServerDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 openServerDay = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpenServerDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        openServerDay_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo> shop_ =
        java.util.Collections.emptyList();
      private void ensureShopIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          shop_ = new java.util.ArrayList<com.gzbz.protobuf.ZhenYuMsg.ShopInfo>(shop_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gzbz.protobuf.ZhenYuMsg.ShopInfo, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder, com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder> shopBuilder_;

      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo> getShopList() {
        if (shopBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shop_);
        } else {
          return shopBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public int getShopCount() {
        if (shopBuilder_ == null) {
          return shop_.size();
        } else {
          return shopBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo getShop(int index) {
        if (shopBuilder_ == null) {
          return shop_.get(index);
        } else {
          return shopBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder setShop(
          int index, com.gzbz.protobuf.ZhenYuMsg.ShopInfo value) {
        if (shopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopIsMutable();
          shop_.set(index, value);
          onChanged();
        } else {
          shopBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder setShop(
          int index, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder builderForValue) {
        if (shopBuilder_ == null) {
          ensureShopIsMutable();
          shop_.set(index, builderForValue.build());
          onChanged();
        } else {
          shopBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder addShop(com.gzbz.protobuf.ZhenYuMsg.ShopInfo value) {
        if (shopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopIsMutable();
          shop_.add(value);
          onChanged();
        } else {
          shopBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder addShop(
          int index, com.gzbz.protobuf.ZhenYuMsg.ShopInfo value) {
        if (shopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopIsMutable();
          shop_.add(index, value);
          onChanged();
        } else {
          shopBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder addShop(
          com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder builderForValue) {
        if (shopBuilder_ == null) {
          ensureShopIsMutable();
          shop_.add(builderForValue.build());
          onChanged();
        } else {
          shopBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder addShop(
          int index, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder builderForValue) {
        if (shopBuilder_ == null) {
          ensureShopIsMutable();
          shop_.add(index, builderForValue.build());
          onChanged();
        } else {
          shopBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder addAllShop(
          java.lang.Iterable<? extends com.gzbz.protobuf.ZhenYuMsg.ShopInfo> values) {
        if (shopBuilder_ == null) {
          ensureShopIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, shop_);
          onChanged();
        } else {
          shopBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder clearShop() {
        if (shopBuilder_ == null) {
          shop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          shopBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public Builder removeShop(int index) {
        if (shopBuilder_ == null) {
          ensureShopIsMutable();
          shop_.remove(index);
          onChanged();
        } else {
          shopBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder getShopBuilder(
          int index) {
        return getShopFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder getShopOrBuilder(
          int index) {
        if (shopBuilder_ == null) {
          return shop_.get(index);  } else {
          return shopBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public java.util.List<? extends com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder> 
           getShopOrBuilderList() {
        if (shopBuilder_ != null) {
          return shopBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shop_);
        }
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder addShopBuilder() {
        return getShopFieldBuilder().addBuilder(
            com.gzbz.protobuf.ZhenYuMsg.ShopInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder addShopBuilder(
          int index) {
        return getShopFieldBuilder().addBuilder(
            index, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .zhenYu.com.gzbz.protobuf.ShopInfo shop = 3;</code>
       */
      public java.util.List<com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder> 
           getShopBuilderList() {
        return getShopFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gzbz.protobuf.ZhenYuMsg.ShopInfo, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder, com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder> 
          getShopFieldBuilder() {
        if (shopBuilder_ == null) {
          shopBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gzbz.protobuf.ZhenYuMsg.ShopInfo, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder, com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder>(
                  shop_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          shop_ = null;
        }
        return shopBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002)
    }

    // @@protoc_insertion_point(class_scope:zhenYu.com.gzbz.protobuf.S2C_ShopInfo_29002)
    private static final com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002();
    }

    public static com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C_ShopInfo_29002>
        PARSER = new com.google.protobuf.AbstractParser<S2C_ShopInfo_29002>() {
      @java.lang.Override
      public S2C_ShopInfo_29002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_ShopInfo_29002(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_ShopInfo_29002> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_ShopInfo_29002> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.ZhenYuMsg.S2C_ShopInfo_29002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShopInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhenYu.com.gzbz.protobuf.ShopInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required int32 buy = 2;</code>
     * @return Whether the buy field is set.
     */
    boolean hasBuy();
    /**
     * <code>required int32 buy = 2;</code>
     * @return The buy.
     */
    int getBuy();
  }
  /**
   * Protobuf type {@code zhenYu.com.gzbz.protobuf.ShopInfo}
   */
  public  static final class ShopInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zhenYu.com.gzbz.protobuf.ShopInfo)
      ShopInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShopInfo.newBuilder() to construct.
    private ShopInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShopInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShopInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShopInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              buy_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.ZhenYuMsg.ShopInfo.class, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int BUY_FIELD_NUMBER = 2;
    private int buy_;
    /**
     * <code>required int32 buy = 2;</code>
     * @return Whether the buy field is set.
     */
    public boolean hasBuy() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 buy = 2;</code>
     * @return The buy.
     */
    public int getBuy() {
      return buy_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, buy_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buy_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.ZhenYuMsg.ShopInfo)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.ZhenYuMsg.ShopInfo other = (com.gzbz.protobuf.ZhenYuMsg.ShopInfo) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasBuy() != other.hasBuy()) return false;
      if (hasBuy()) {
        if (getBuy()
            != other.getBuy()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasBuy()) {
        hash = (37 * hash) + BUY_FIELD_NUMBER;
        hash = (53 * hash) + getBuy();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.ZhenYuMsg.ShopInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhenYu.com.gzbz.protobuf.ShopInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhenYu.com.gzbz.protobuf.ShopInfo)
        com.gzbz.protobuf.ZhenYuMsg.ShopInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.ZhenYuMsg.ShopInfo.class, com.gzbz.protobuf.ZhenYuMsg.ShopInfo.Builder.class);
      }

      // Construct using com.gzbz.protobuf.ZhenYuMsg.ShopInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        buy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo getDefaultInstanceForType() {
        return com.gzbz.protobuf.ZhenYuMsg.ShopInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo build() {
        com.gzbz.protobuf.ZhenYuMsg.ShopInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.ShopInfo buildPartial() {
        com.gzbz.protobuf.ZhenYuMsg.ShopInfo result = new com.gzbz.protobuf.ZhenYuMsg.ShopInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.buy_ = buy_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.ZhenYuMsg.ShopInfo) {
          return mergeFrom((com.gzbz.protobuf.ZhenYuMsg.ShopInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.ZhenYuMsg.ShopInfo other) {
        if (other == com.gzbz.protobuf.ZhenYuMsg.ShopInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBuy()) {
          setBuy(other.getBuy());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasBuy()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.ZhenYuMsg.ShopInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.ZhenYuMsg.ShopInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int buy_ ;
      /**
       * <code>required int32 buy = 2;</code>
       * @return Whether the buy field is set.
       */
      public boolean hasBuy() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 buy = 2;</code>
       * @return The buy.
       */
      public int getBuy() {
        return buy_;
      }
      /**
       * <code>required int32 buy = 2;</code>
       * @param value The buy to set.
       * @return This builder for chaining.
       */
      public Builder setBuy(int value) {
        bitField0_ |= 0x00000002;
        buy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 buy = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        buy_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zhenYu.com.gzbz.protobuf.ShopInfo)
    }

    // @@protoc_insertion_point(class_scope:zhenYu.com.gzbz.protobuf.ShopInfo)
    private static final com.gzbz.protobuf.ZhenYuMsg.ShopInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.ZhenYuMsg.ShopInfo();
    }

    public static com.gzbz.protobuf.ZhenYuMsg.ShopInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ShopInfo>
        PARSER = new com.google.protobuf.AbstractParser<ShopInfo>() {
      @java.lang.Override
      public ShopInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShopInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShopInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShopInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.ZhenYuMsg.ShopInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_Buy_29003OrBuilder extends
      // @@protoc_insertion_point(interface_extends:zhenYu.com.gzbz.protobuf.C2S_Buy_29003)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code zhenYu.com.gzbz.protobuf.C2S_Buy_29003}
   */
  public  static final class C2S_Buy_29003 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zhenYu.com.gzbz.protobuf.C2S_Buy_29003)
      C2S_Buy_29003OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_Buy_29003.newBuilder() to construct.
    private C2S_Buy_29003(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_Buy_29003() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S_Buy_29003();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_Buy_29003(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.class, com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003)) {
        return super.equals(obj);
      }
      com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 other = (com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zhenYu.com.gzbz.protobuf.C2S_Buy_29003}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zhenYu.com.gzbz.protobuf.C2S_Buy_29003)
        com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.class, com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.Builder.class);
      }

      // Construct using com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzbz.protobuf.ZhenYuMsg.internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 getDefaultInstanceForType() {
        return com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.getDefaultInstance();
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 build() {
        com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 buildPartial() {
        com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 result = new com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003) {
          return mergeFrom((com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 other) {
        if (other == com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zhenYu.com.gzbz.protobuf.C2S_Buy_29003)
    }

    // @@protoc_insertion_point(class_scope:zhenYu.com.gzbz.protobuf.C2S_Buy_29003)
    private static final com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003();
    }

    public static com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_Buy_29003>
        PARSER = new com.google.protobuf.AbstractParser<C2S_Buy_29003>() {
      @java.lang.Override
      public C2S_Buy_29003 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_Buy_29003(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_Buy_29003> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_Buy_29003> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gzbz.protobuf.ZhenYuMsg.C2S_Buy_29003 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ZhenYu.proto\022\030zhenYu.com.gzbz.protobuf" +
      "\"\024\n\022C2S_ShopInfo_29001\"m\n\022S2C_ShopInfo_2" +
      "9002\022\016\n\006ActDay\030\001 \002(\005\022\025\n\ropenServerDay\030\002 " +
      "\002(\005\0220\n\004shop\030\003 \003(\0132\".zhenYu.com.gzbz.prot" +
      "obuf.ShopInfo\"#\n\010ShopInfo\022\n\n\002id\030\001 \002(\005\022\013\n" +
      "\003buy\030\002 \002(\005\"\033\n\rC2S_Buy_29003\022\n\n\002id\030\001 \002(\005B" +
      " \n\021com.gzbz.protobufB\tZhenYuMsgH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhenYu_com_gzbz_protobuf_C2S_ShopInfo_29001_descriptor,
        new java.lang.String[] { });
    internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhenYu_com_gzbz_protobuf_S2C_ShopInfo_29002_descriptor,
        new java.lang.String[] { "ActDay", "OpenServerDay", "Shop", });
    internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhenYu_com_gzbz_protobuf_ShopInfo_descriptor,
        new java.lang.String[] { "Id", "Buy", });
    internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhenYu_com_gzbz_protobuf_C2S_Buy_29003_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
