package com.gzbz.gameDefine;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class PlayerDefine {
   public static int PLAYER_LV = 1;
   public static int PLAYER_EXP = 2;
   public static int PLAYER_VIP_LV = 3;
   public static int PLAYER_VIP_EXP = 4;
   public static int PLAYER_UNION_ACTIVE = 5;
   public static int PLAYER_UNION_ACTIVE_LV = 6;
   public static int PLAYER_ARENA_PRAISE = 7;
   public static int PLAYER_COPPER = 8;
   public static int PLAYER_GOLD = 9;
   public static int PLAYER_HERO_EXP = 10;
   public static int PLAYER_INFOMATION = 11;
   public static int PLAYER_FRIEND = 12;
   public static int PLAYER_ACTIVE = 13;
   public static int PLAYER_SOUL = 14;
   public static int PLAYER_MANA = 15;
   public static int PLAYER_RENOW = 16;
   public static int PLAYER_UNION_CONTRIBUTION = 17;
   public static int PLAYER_BLESSING = 18;
   public static int PLAYER_HONOR = 19;
   public static int PLAYER_RECRUIT_STONE = 20;
   public static int PLAYER_SKIN_CRYSTAL = 21;
   public static int PLAYER_DRESS = 22;
   public static int PLAYER_PVP_POINTS = 23;
   public static int PLAYER_COMBAT_POWER = 24;
   public static int PLAYER_WARRIOR_SIGNET_TRACE = 25;
   public static int PLAYER_PRAY_SCORE = 26;
   public static int PLAYER_CONQUE_COIN = 27;
   public static int PLAYER_MILITARY = 28;
   public static int PLAYER_COOPERATION = 29;
   public static int PLAYER_WIN_PLAINS = 30;
   public static int PLAYER_TOP_MATCH = 31;
   public static int PLAYER_HERO_CLUB = 32;
   public static int PLAYER_BARBARIAN_INTEGRAL = 33;
   public static int PLAYER_PR_FAST_FIGHT = 34;
   public static int PLAYER_PR_CHI_BI = 35;
   public static int PLAYER_PR_ADVENTURE_SENIOR = 36;
   public static int PLAYER_PR_ADVENTURE_LUXURY = 37;
   public static int PLAYER_HERO_RAISE_INTEGRAL = 38;
   public static int PLAYER_LADDER_PVP_INTEGRAL = 39;
   public static int PLAYER_PR_DRAGON = 40;
   public static int PLAYER_PR_TRANSPORT = 41;
   public static int PLAYER_ACT_SOLDIER_BOOK = 42;
   public static int PLAYER_ACT_SEAL = 43;
   public static int PLAYER_ACT_COUNTRY_BOOK = 44;
   public static int PLAYER_ACT_QIN = 45;
   public static int PLAYER_MEDICINE = 46;
   public static int PLAYER_POISON = 47;
   public static int PLAYER_BUSINESSMAN = 48;
   public static int PLAYER_TONGTIAN_ORDER = 49;
   public static int PLAYER_TRAIL_KING = 50;
   public static int PLAYER_PR_MARQUIS = 51;
   public static int PLAYER_CHIBI_CHIP = 52;
   public static int PLAYER_PEAK_LV = 53;
   public static int PLAYER_ACT_OFFER = 54;
   public static int PLAYER_CHAPTER_EXP = 55;
   public static int PLAYER_COUNTRY_ATT_TOKEN = 56;
   public static int PLAYER_COUNTRY_MOVE_TOKEN = 57;
   public static int PLAYER_SEVEN_BARBARIAN = 58;
   public static int PLAYER_COUNTRY_WAR_SCORE = 59;
   public static int PLAYER_STONE_MATERIAL = 60;
   public static int PLAYER_HERO_THEME = 61;
   public static int PLAYER_FAIRYLAND = 62;
   public static int PLAYER_HERO_DRESS_COIN = 63;
   public static int PLAYER_FENGMO_POINT = 64;
   public static int PLAYER_PET_EXP = 65;
   public static int PLAYER_OFFER_POINT = 66;
   public static int PLAYER_PR_KING_CP = 67;
   public static int PLAYER_PR_PET = 68;
   public static int PLAYER_PR_MINE = 69;
   public static int PALACE_TITLE = 70;
   public static int PALACE_POINT = 71;
   public static int DRAGON_WAR_POINT = 72;
   public static int PLAYER_TONGTIAN_TOKEN = 73;
   public static int PLAYER_FIRST_YEAR_TREASURE = 74;
   public static int PLAYER_STONEHENGE_POINT = 75;
   public static int PLAYER_DIAMOND = 76;
   public static int PLAYER_DIAMOND_CHIP = 77;
   public static int PLAYER_FORTUNE_POINT = 78;
   public static int PLAYER_FIRE_POINT = 79;
   public static int PLAYER_ANCIENT_SWORD_POINT = 80;
   public static int PLAYER_WEEKLY_CARD_POINT = 81;
   public static int PLAYER_NEW_WEEK_TREASURE = 82;
   public static int PLAYER_TRAIL_EMPEROR = 83;
   public static int PLAYER_PRI_SUPREME_WAR_ORDER = 84;
   public static int PLAYER_PRI_SUPREME_POINT = 85;
   public static int PLAYER_HERO_CARD = 86;
   public static int PLAYER_LING_LONG_BOOK = 87;
   public static int PLAYER_DRAGON_CAVE = 88;
   public static int PLAYER_ID = 99;
   public static int PLAYER_HEROBAG_BUYNUM = 100;
   public static int PLAYER_COMBAT_POWER_101 = 101;
   public static int PLAYER_CHAPTER_ID = 102;
   public static int PLAYER_PRIVILEGE_LV = 103;
   public static int PLAYER_NAME = 104;
   public static int PLAYER_HEAD = 105;
   public static int PLAYER_HEADFRAME = 106;
   public static int PLAYER_UNION_ID = 107;
   public static int PLAYER_RECHARGE_DAILY_TOTAL = 108;
   public static int PLAYER_RECHARGE_TOTAL = 109;
   public static int PLAYER_RECHARGE_TOTAL_DAY = 110;
   public static int PLAYER_PRESTIGE = 111;
   public static int PLAYER_MONARCHID = 112;
   public static int PLAYER_PROVINCE = 113;
   public static int PLAYER_SEX = 114;
   public static int PLAYER_GUIDE_ID = 115;
   public static int PLAYER_STORY_ID = 116;
   public static int PLAYER_DAILY_RESET = 117;
   public static int PLAYER_KEY1 = 118;
   public static int PLAYER_MASK = 119;
   public static int PLAYER_AGE = 120;
   public static int PLAYER_TODAY_ONLINE_TIME = 121;
   public static int PLAYER_TODAY_ONLINE_LIMIT = 122;
   public static int PLAYER_RECHARGE_MONTH_TOTAL = 123;
   public static int PLAYER_TOTAL_ONLINE_TIME = 124;
   public static int PLAYER_BIRTH_TIME = 125;
   public static int RE_CONNECT = 126;
   public static int PLAYER_RUNE_STONE = 127;
   public static int PLAYER_TYPE = 128;
   public static int HERO_HIGHEST_LV = 129;
   public static int HERO_HIGHEST_STAR = 130;
   public static int PLAYER_HIGHEST_POWER = 131;
   public static int OPEN_SERVER_TIME = 132;
   public static int PLAYER_SHOW_VIP_LEVEL = 133;
   public static int PLAYER_LEAVE_TIME = 134;
   public static int PLAYER_JOIN_UNION_CD = 135;
   public static int CLIENT_VERSION = 136;
   public static int PLAYER_SECOND_TITLE = 137;
   public static int ACT_ARTIFACT_FLAG = 138;
   public static int PET_BAG_NUM = 139;
   public static int PET_BAG_BUY_NUM = 140;
   public static int CHAT_BUBBLE = 141;
   public static int PLAYER_HISTORY_CONTRIBUTION = 142;
   public static int PLAYER_PROVINCE_ID = 143;
   public static int PLAYER_CITY_ID = 144;
   public static int UNION_COPY_CHALLENGE = 145;
   public static int UNION_COPY_BUY = 146;
   public static int SERVER_ID = 147;
   public static int STAR_13_HERO_NUM = 148;
   public static int HERO_PROMOTE_LEVEL = 149;
   public static int HERO_PROMOTE_STAGE = 150;
   public static int CROSS_PK_CD = 151;
   public static int CROSS_PK_FLUSH_CD = 152;
   public static int CUSTOM_FACE_STATE = 153;
   public static int ALL_SERVER_ID = 154;
   public static int MAIN_SERVER_ID = 155;
   public static int COME_BACK_ACT_REG = 156;
   public static int IS_AFTER_MERGE = 157;
   public static int QQ_WAN_KA_LV = 158;
   public static int QQ_WAN_KA_LOGO = 159;
   public static int COIN_TOTAL_RECHARGE = 160;
   public static HashMap<Integer, String> map = new HashMap();
   public static final List<Integer> ACCOUNT_TYPE_PLAYER_LIST = new ArrayList();
   public static final int ACCOUNT_TYPE_PLAYER = 0;
   public static final int ACCOUNT_TYPE_ROBOT_1 = 1;
   public static final int ACCOUNT_TYPE_ROBOT_2 = 2;
   public static final int ACCOUNT_TYPE_ROBOT_5 = 5;
   public static final int ACCOUNT_TYPE_INNER_PLAYER = 998;
   public static final int ACCOUNT_TYPE_GM_PLAYER = 999;
   public static final int SEX_MALE = 0;
   public static final int SEX_FEMALE = 1;
   public static final int GUIDEID_GET = 1;
   public static final int GUIDEID_RECORD = 2;
   public static final int INIT_HEAD_FRAME = 30001;

   static {
      ACCOUNT_TYPE_PLAYER_LIST.add(0);
      ACCOUNT_TYPE_PLAYER_LIST.add(998);
      ACCOUNT_TYPE_PLAYER_LIST.add(999);
      map.put(PLAYER_LV, "lv");
      map.put(PLAYER_EXP, "exp");
      map.put(PLAYER_VIP_LV, "vip_lv");
      map.put(PLAYER_VIP_EXP, "vip_exp");
      map.put(PLAYER_UNION_ACTIVE, "union_active");
      map.put(PLAYER_UNION_ACTIVE_LV, "union_active_lv");
      map.put(PLAYER_ARENA_PRAISE, "arena_praise");
      map.put(PLAYER_COPPER, "copper");
      map.put(PLAYER_GOLD, "gold");
      map.put(PLAYER_HERO_EXP, "hero_exp");
      map.put(PLAYER_INFOMATION, "infomation");
      map.put(PLAYER_FRIEND, "friend");
      map.put(PLAYER_ACTIVE, "active");
      map.put(PLAYER_SOUL, "soul");
      map.put(PLAYER_MANA, "mana");
      map.put(PLAYER_RENOW, "renow");
      map.put(PLAYER_UNION_CONTRIBUTION, "union_contribution");
      map.put(PLAYER_BLESSING, "blessing");
      map.put(PLAYER_HONOR, "honor");
      map.put(PLAYER_RECRUIT_STONE, "recruit_stone");
      map.put(PLAYER_SKIN_CRYSTAL, "skin_crystal");
      map.put(PLAYER_DRESS, "dress");
      map.put(PLAYER_PVP_POINTS, "pvp_points");
      map.put(PLAYER_COMBAT_POWER, "combat_power");
      map.put(PLAYER_WARRIOR_SIGNET_TRACE, "signetTrace");
      map.put(PLAYER_PRAY_SCORE, "prayScore");
      map.put(PLAYER_CONQUE_COIN, "conqueCoin");
      map.put(PLAYER_MILITARY, "military");
      map.put(PLAYER_COOPERATION, "cooperation");
      map.put(PLAYER_WIN_PLAINS, "winPlains");
      map.put(PLAYER_TOP_MATCH, "topMatch");
      map.put(PLAYER_HERO_CLUB, "heroClub");
      map.put(PLAYER_BARBARIAN_INTEGRAL, "barbarian_integral");
      map.put(PLAYER_PR_FAST_FIGHT, "privilege_fast_fight");
      map.put(PLAYER_PR_CHI_BI, "privilege_chi_bi");
      map.put(PLAYER_PR_ADVENTURE_SENIOR, "privilege_adventure_senior");
      map.put(PLAYER_PR_ADVENTURE_LUXURY, "privilege_adventure_luxury");
      map.put(PLAYER_HERO_RAISE_INTEGRAL, "hero_raise_integral");
      map.put(PLAYER_LADDER_PVP_INTEGRAL, "ladder_pvp_integral");
      map.put(PLAYER_PR_DRAGON, "privilege_dragon");
      map.put(PLAYER_PR_TRANSPORT, "privilege_transport");
      map.put(PLAYER_ACT_SOLDIER_BOOK, "act_soldier_book");
      map.put(PLAYER_ACT_SEAL, "act_seal");
      map.put(PLAYER_ACT_COUNTRY_BOOK, "act_country_book");
      map.put(PLAYER_ACT_QIN, "act_qin");
      map.put(PLAYER_MEDICINE, "war_medicine");
      map.put(PLAYER_POISON, "war_poison");
      map.put(PLAYER_BUSINESSMAN, "war_businessman");
      map.put(PLAYER_TONGTIAN_ORDER, "tongtian_order");
      map.put(PLAYER_TRAIL_KING, "trail_king");
      map.put(PLAYER_PR_MARQUIS, "privilege_marquis");
      map.put(PLAYER_CHIBI_CHIP, "chibi_chip");
      map.put(PLAYER_PEAK_LV, "peak_lv");
      map.put(PLAYER_ACT_OFFER, "act_offer");
      map.put(PLAYER_CHAPTER_EXP, "chapter_exp");
      map.put(PLAYER_COUNTRY_ATT_TOKEN, "att_token");
      map.put(PLAYER_COUNTRY_MOVE_TOKEN, "move_token");
      map.put(PLAYER_SEVEN_BARBARIAN, "seven_barbarian");
      map.put(PLAYER_COUNTRY_WAR_SCORE, "country_war_score");
      map.put(PLAYER_STONE_MATERIAL, "stone_material");
      map.put(PLAYER_HERO_THEME, "hero_theme");
      map.put(PLAYER_FAIRYLAND, "fairyland");
      map.put(PLAYER_HERO_DRESS_COIN, "hero_dress_coin");
      map.put(PLAYER_FENGMO_POINT, "fengmo_point");
      map.put(PLAYER_PET_EXP, "pet_exp");
      map.put(PLAYER_OFFER_POINT, "offer_point");
      map.put(PLAYER_PR_KING_CP, "privilege_kingcp");
      map.put(PLAYER_PR_PET, "privilege_pet");
      map.put(PLAYER_PR_MINE, "privilege_mine");
      map.put(PALACE_TITLE, "palaceTitle");
      map.put(PALACE_POINT, "palacePoint");
      map.put(DRAGON_WAR_POINT, "dragonWarPoint");
      map.put(PLAYER_TONGTIAN_TOKEN, "tongtian_token");
      map.put(PLAYER_FIRST_YEAR_TREASURE, "first_year_treasure");
      map.put(PLAYER_STONEHENGE_POINT, "stonehenge_integral");
      map.put(PLAYER_DIAMOND, "diamond");
      map.put(PLAYER_DIAMOND_CHIP, "diamond_chip");
      map.put(PLAYER_FORTUNE_POINT, "fortune_point");
      map.put(PLAYER_FIRE_POINT, "hero_fire_coin");
      map.put(PLAYER_WEEKLY_CARD_POINT, "weekly_card_point");
      map.put(PLAYER_ANCIENT_SWORD_POINT, "ancient_sword_point");
      map.put(PLAYER_NEW_WEEK_TREASURE, "new_week_treasure");
      map.put(PLAYER_TRAIL_EMPEROR, "trail_emperor");
      map.put(PLAYER_PRI_SUPREME_WAR_ORDER, "pri_supreme_war_order");
      map.put(PLAYER_PRI_SUPREME_POINT, "supreme_point");
      map.put(PLAYER_HERO_CARD, "hero_card");
      map.put(PLAYER_LING_LONG_BOOK, "lingLongBook");
      map.put(PLAYER_DRAGON_CAVE, "dragonCave");
   }
}
