package com.gzbz.gameDefine;

public interface ResourceDefine {
   int TYPE_ONE_PROPERTY = 1;
   int TYPE_ONE_ITEM = 2;
   int TYPE_ONE_HERO = 3;
   int TYPE_SPECIAL_AWARD = 10;
   int TYPE_BOX_AWARD = 11;
   int TYPE_SELECT_PACKAGE = 12;
   int TYPE_CHIP_EXCHANGE = 13;
   int TYPE_CHIP_RANDOM_EXCHANGE = 14;
   int TYPE_CHIP_VICE_COMPOSE = 16;
   int TYPE_CHIP_GEM_COMPOSE = 17;
   int TYPE_UNLOCK_BEAUTY = 18;
   int TYPE_CUSTOM_RUNESTONE = 19;
   int TYPE_BOX = 20;
   int TYPE_ARTIFACT_DRESS = 21;
   int TYPE_WAR_HORSE_RANDOM = 22;
   int TYPE_WAR_HORSE = 23;
   int TYPE_ARTIFACT_DRESS_FORVER = 25;
   int TYPE_EQUIP_EXTRA_COMPOSE = 26;
   int TYPE_CUSTOM_WARRIORSIGNET = 27;
   int TYPE_WAR_HORSE_ITEM = 30;
   int TYPE_COMPOSE_ARTIFACT_DRESS = 31;
   int TYPE_COMPOSE_BEAUTY = 32;
   int TYPE_CHANGE_PRESTIGE = 35;
   int TYPE_CALL_RECHARGE = 88;
   int TYPE_ADD_QUICK_BATTLE_TIMES = 87;
   int TYPE_ADD_GIFT = 86;
   int TYPE_FAST_BATTLE = 90;
}
